// 50 original Advanced Math questions, written for this app. Not College Board content, so these can ship
// in the repo and reach every visitor.
//
// Seventeen questions each for Equivalent expressions and for Nonlinear equations and systems, and sixteen
// for Nonlinear functions. Every answer is re-derived independently in tests/questions.test.js.

const DOMAIN = 'Advanced Math';

const mc = (id, skill, difficulty, stem, choices, answer, rationale) => ({
  id: `og-${id}`, section: 'MATH', domain: DOMAIN, skill, difficulty, stem,
  choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })),
  answer, rationale, source: 'original',
});

const spr = (id, skill, difficulty, stem, answer, rationale) => ({
  id: `og-${id}`, section: 'MATH', domain: DOMAIN, skill, difficulty, stem,
  choices: null, answer, rationale, source: 'original',
});

const EQV = 'Equivalent expressions';
const NLE = 'Nonlinear equations in one variable and systems of equations in two variables';
const NLF = 'Nonlinear functions';

export const ADVANCED_MATH_QUESTIONS = [
  // ---- Equivalent expressions ----
  mc('adv-01', EQV, 'Easy', 'Which expression is equivalent to (x + 4)²?',
    ['x² + 16', 'x² + 8x + 16', 'x² + 4x + 16', '2x + 8'], 'B',
    'Squaring a binomial gives (x + 4)(x + 4) = x² + 4x + 4x + 16 = x² + 8x + 16. Choice A drops the middle term, which is the most common error.'),
  mc('adv-02', EQV, 'Easy', 'Which expression is equivalent to 3x(2x − 5)?',
    ['6x² − 15x', '6x² − 5', '5x² − 15x', '6x − 15'], 'A',
    'Distribute 3x across both terms: 3x · 2x = 6x² and 3x · (−5) = −15x, giving 6x² − 15x.'),
  mc('adv-03', EQV, 'Medium', 'Which expression is equivalent to (2x − 3)(x + 5)?',
    ['2x² − 15', '2x² + 7x − 15', '2x² + 13x − 15', '2x² − 7x − 15'], 'B',
    'Multiplying out gives 2x² + 10x − 3x − 15. Combining the middle terms gives 2x² + 7x − 15.'),
  mc('adv-04', EQV, 'Medium', 'Which expression is equivalent to x² − 9?',
    ['(x − 3)(x + 3)', '(x − 9)(x + 1)', '(x − 3)²', '(x + 3)²'], 'A',
    'This is a difference of two squares: x² − 3² factors as (x − 3)(x + 3). Choice C expands to x² − 6x + 9, which has an extra middle term.'),
  mc('adv-05', EQV, 'Medium', 'Which expression is equivalent to x² + 7x + 12?',
    ['(x + 2)(x + 6)', '(x + 1)(x + 12)', '(x + 3)(x + 4)', '(x − 3)(x − 4)'], 'C',
    'Look for two numbers that multiply to 12 and add to 7: 3 and 4. So the expression factors as (x + 3)(x + 4).'),
  mc('adv-06', EQV, 'Hard', 'For x ≠ 2, which expression is equivalent to (x² − 4)/(x − 2)?',
    ['x − 2', 'x + 2', 'x² − 2', '2'], 'B',
    'The numerator factors as (x − 2)(x + 2). Canceling the common factor of x − 2, which is allowed because x ≠ 2, leaves x + 2.'),
  spr('adv-07', EQV, 'Medium', 'If 2(x + 3) + 4x = 6x + k for every value of x, what is the value of k?', ['6'],
    'The left side expands to 2x + 6 + 4x = 6x + 6. For the two sides to match for every x, the constant terms must be equal, so k = 6.'),
  mc('adv-08', EQV, 'Medium', 'Which expression is equivalent to 4x² − 12x + 9?',
    ['(2x − 3)²', '(2x + 3)²', '(4x − 3)²', '(2x − 9)²'], 'A',
    'Since (2x)² = 4x² and 3² = 9, test (2x − 3)²: it expands to 4x² − 12x + 9, which matches. Choice B gives +12x instead.'),
  mc('adv-09', EQV, 'Hard', 'Which expression is equivalent to (3x²y³)(2xy²)?',
    ['6x³y⁵', '5x³y⁵', '6x²y⁶', '6x³y⁶'], 'A',
    'Multiply the coefficients and add the exponents of like bases: 3 · 2 = 6, x² · x = x³, and y³ · y² = y⁵, giving 6x³y⁵. Choice B adds the coefficients instead of multiplying them.'),
  mc('adv-10', EQV, 'Medium', 'For x ≠ 0, which expression is equivalent to x⁶/x²?',
    ['x³', 'x⁴', 'x⁸', 'x¹²'], 'B',
    'Dividing powers of the same base subtracts the exponents: 6 − 2 = 4, so the result is x⁴. Choice C adds them and choice D multiplies them.'),
  mc('adv-11', EQV, 'Hard', 'For x > 0, which expression is equivalent to √(49x⁴)?',
    ['7x²', '7x⁴', '49x²', '7x'], 'A',
    'The square root of a product is the product of the square roots: √49 = 7 and √(x⁴) = x², so the result is 7x².'),
  spr('adv-12', EQV, 'Medium', 'If (x + a)² = x² + 10x + 25 for every value of x, what is the value of a?', ['5'],
    'Expanding gives x² + 2ax + a². Matching the middle terms, 2a = 10, so a = 5, and a² = 25 confirms it.'),
  mc('adv-13', EQV, 'Hard', 'Which expression is equivalent to (x + 2)(x² − 2x + 4)?',
    ['x³ + 8', 'x³ − 8', 'x³ + 4x + 8', 'x³ + 2x² + 8'], 'A',
    'Multiplying out gives x³ − 2x² + 4x + 2x² − 4x + 8. The x² terms cancel and the x terms cancel, leaving x³ + 8.'),
  mc('adv-14', EQV, 'Medium', 'Which expression is equivalent to 5x² + 10x?',
    ['5x(x + 2)', '5x(x + 10)', '5(x² + 10x)', 'x(5x + 2)'], 'A',
    'The greatest common factor of both terms is 5x, and 5x² + 10x = 5x(x + 2). Each of the other choices expands to something different.'),
  mc('adv-15', EQV, 'Medium', 'Which expression is equivalent to (x − 5)(x + 5)?',
    ['x² − 25', 'x² + 25', 'x² − 10x + 25', 'x² − 10x − 25'], 'A',
    'The middle terms −5x and +5x cancel, leaving x² − 25. Choice C is the expansion of (x − 5)².'),
  spr('adv-16', EQV, 'Hard', 'If 3x² − 12 = 3(x² + c) for every value of x, what is the value of c?', ['-4', '−4'],
    'The right side expands to 3x² + 3c. Matching the constant terms gives 3c = −12, so c = −4.'),
  mc('adv-17', EQV, 'Hard', 'Which expression is equivalent to (a + b)² − (a − b)²?',
    ['0', '2b²', '4ab', '2a² + 2b²'], 'C',
    'The first square is a² + 2ab + b² and the second is a² − 2ab + b². Subtracting cancels a² and b² and leaves 2ab − (−2ab) = 4ab.'),

  // ---- Nonlinear equations in one variable and systems of equations in two variables ----
  mc('adv-18', NLE, 'Easy', 'If x² = 49, what is the positive solution for x?',
    ['7', '9', '24.5', '2401'], 'A',
    'Taking the square root of both sides gives x = 7 or x = −7, so the positive solution is 7. Choice C halves 49 and choice D squares it.'),
  spr('adv-19', NLE, 'Easy', 'What is the sum of the solutions to x² − 5x + 6 = 0?', ['5'],
    'The equation factors as (x − 2)(x − 3) = 0, so the solutions are 2 and 3 and their sum is 5.'),
  mc('adv-20', NLE, 'Medium', 'Which value is a solution to x² + 3x − 10 = 0?',
    ['−10', '−5', '5', '10'], 'B',
    'The equation factors as (x + 5)(x − 2) = 0, so the solutions are −5 and 2. Only −5 appears among the choices.'),
  mc('adv-21', NLE, 'Medium', 'How many distinct real solutions does x² − 6x + 9 = 0 have?',
    ['0', '1', '2', 'Infinitely many'], 'B',
    'The left side factors as (x − 3)², so the only solution is x = 3. A perfect square set equal to zero has exactly one distinct solution.'),
  spr('adv-22', NLE, 'Medium', 'What is the product of the solutions to x² − 7x + 12 = 0?', ['12'],
    'The equation factors as (x − 3)(x − 4) = 0, so the solutions are 3 and 4 and their product is 12.'),
  mc('adv-23', NLE, 'Hard', 'If 2x² − 8 = 0, what is the positive solution for x?',
    ['2', '4', '8', '16'], 'A',
    'Add 8 and divide by 2 to get x² = 4, so x = 2 or x = −2. The positive solution is 2. Choice B is the value of x², not x.'),
  mc('adv-24', NLE, 'Hard', 'The equation x² + 4x + c = 0 has exactly one real solution. What is the value of c?',
    ['−4', '0', '2', '4'], 'D',
    'A quadratic has exactly one real solution when its discriminant b² − 4ac is zero. Here 4² − 4(1)(c) = 16 − 4c = 0, so c = 4, and the equation becomes (x + 2)².'),
  spr('adv-25', NLE, 'Hard', 'What is the sum of the solutions to x² = 6x − 8?', ['6'],
    'Rewrite as x² − 6x + 8 = 0, which factors as (x − 2)(x − 4) = 0. The solutions are 2 and 4, so the sum is 6.'),
  mc('adv-26', NLE, 'Medium', 'If √(x + 5) = 4, what is the value of x?',
    ['3', '9', '11', '21'], 'C',
    'Square both sides to get x + 5 = 16, so x = 11. Choice C checks out because √16 = 4.'),
  mc('adv-27', NLE, 'Hard', 'If (x − 1)² = 16, what is the greater solution for x?',
    ['3', '4', '5', '17'], 'C',
    'Taking square roots gives x − 1 = 4 or x − 1 = −4, so x = 5 or x = −3. The greater solution is 5. Choice D comes from adding 1 to 16 without taking the root.'),
  spr('adv-28', NLE, 'Medium', 'If x² + 2x = 15, what is the positive solution for x?', ['3'],
    'Rewrite as x² + 2x − 15 = 0, which factors as (x + 5)(x − 3) = 0. The solutions are −5 and 3, so the positive one is 3.'),
  mc('adv-29', NLE, 'Hard', 'How many solutions does the system y = x² and y = 4x − 3 have?',
    ['0', '1', '2', '3'], 'C',
    'Setting the right sides equal gives x² = 4x − 3, or x² − 4x + 3 = 0, which factors as (x − 1)(x − 3) = 0. Two values of x work, so the system has two solutions.'),
  mc('adv-30', NLE, 'Medium', 'If y = x² − 1 and y = 3, which value could x be?',
    ['1', '2', '3', '4'], 'B',
    'Substituting gives x² − 1 = 3, so x² = 4 and x = 2 or x = −2. Only 2 appears among the choices.'),
  spr('adv-31', NLE, 'Hard', 'If 3x² = 27, what is the positive value of x?', ['3'],
    'Divide both sides by 3 to get x² = 9, so x = 3 or x = −3, and the positive value is 3. Dividing first avoids the mistake of taking the square root of 27.'),
  mc('adv-32', NLE, 'Medium', 'What are the solutions to x² − 16 = 0?',
    ['x = 4 only', 'x = −4 only', 'There are no real solutions', 'x = 4 and x = −4'], 'D',
    'The equation gives x² = 16, and both 4 and −4 square to 16, so there are two real solutions. Forgetting the negative root is the usual error.'),
  mc('adv-33', NLE, 'Hard', 'The equation x² + kx + 9 = 0 has exactly one real solution and k is positive. What is the value of k?',
    ['3', '6', '9', '18'], 'B',
    'One real solution means the discriminant is zero: k² − 4(1)(9) = k² − 36 = 0, so k = 6 or k = −6. Since k is positive, k = 6.'),
  mc('adv-34', NLE, 'Medium', 'If 1/x + 1/2 = 1 and x ≠ 0, what is the value of x?',
    ['1/2', '1', '2', '4'], 'C',
    'Subtracting 1/2 from both sides gives 1/x = 1/2, so x = 2.'),

  // ---- Nonlinear functions ----
  mc('adv-35', NLF, 'Easy', 'The function f is defined by f(x) = x² + 1. What is the value of f(3)?',
    ['7', '9', '10', '16'], 'C',
    'Substitute 3 for x: f(3) = 3² + 1 = 9 + 1 = 10. Choice B forgets to add 1 and choice D squares 3 + 1 instead.'),
  mc('adv-36', NLF, 'Medium', 'The function f is defined by f(x) = x² − 4x. What is the value of f(−2)?',
    ['−12', '−4', '4', '12'], 'D',
    'Substitute −2: (−2)² − 4(−2) = 4 + 8 = 12. Both terms are positive because squaring a negative gives a positive and subtracting a negative adds.'),
  mc('adv-37', NLF, 'Medium', 'What is the vertex of the graph of y = (x − 3)² + 2?',
    ['(−3, 2)', '(3, 2)', '(3, −2)', '(2, 3)'], 'B',
    'In vertex form y = (x − h)² + k the vertex is (h, k). Here the expression is (x − 3)², so h = 3, and k = 2, giving (3, 2). The sign of h is the opposite of the one written inside the parentheses.'),
  mc('adv-38', NLF, 'Hard', 'What is the x-coordinate of the vertex of the graph of y = x² − 6x + 5?',
    ['−3', '1', '3', '5'], 'C',
    'For y = ax² + bx + c the vertex sits at x = −b/(2a), which here is −(−6)/(2 · 1) = 3. Choices B and D are the x-intercepts, not the vertex.'),
  spr('adv-39', NLF, 'Medium', 'The function f is defined by f(x) = 2ˣ. What is the value of f(5)?', ['32'],
    'f(5) = 2⁵ = 2 · 2 · 2 · 2 · 2 = 32.'),
  mc('adv-40', NLF, 'Medium', 'The function f is defined by f(x) = 2ˣ. For what value of x does f(x) = 64?',
    ['5', '6', '8', '32'], 'B',
    'Since 2⁶ = 64, x = 6. Choice C comes from dividing 64 by 8 and choice D from halving it.'),
  mc('adv-41', NLF, 'Hard', 'What are the x-intercepts of the graph of y = x² − 9?',
    ['(0, 3) and (0, −3)', '(3, 0) and (−3, 0)', '(9, 0) and (−9, 0)', '(0, 9)'], 'B',
    'Set y = 0 to get x² = 9, so x = 3 or x = −3. An x-intercept has a y-coordinate of 0, which rules out choice A.'),
  mc('adv-42', NLF, 'Medium', 'What is the y-coordinate of the y-intercept of the graph of y = x² + 2x − 8?',
    ['−8', '−4', '2', '8'], 'A',
    'The y-intercept occurs where x = 0, which gives y = 0 + 0 − 8 = −8. For any quadratic in this form the constant term is the y-intercept.'),
  spr('adv-43', NLF, 'Hard', 'The graph of y = x² + 2x − 8 crosses the x-axis at two points. What is the positive x-coordinate of those points?', ['2'],
    'Setting y = 0 gives x² + 2x − 8 = 0, which factors as (x + 4)(x − 2) = 0. The x-intercepts are at x = −4 and x = 2, so the positive one is 2.'),
  mc('adv-44', NLF, 'Medium', 'The function g is defined by g(x) = 3(2)ˣ. What is the value of g(0)?',
    ['0', '1', '3', '6'], 'C',
    'Any nonzero number raised to the power 0 is 1, so g(0) = 3 · 1 = 3. Choice D multiplies 3 by 2 instead.'),
  mc('adv-45', NLF, 'Hard', 'A population of 200 bacteria doubles every 3 years. What is the population after 9 years?',
    ['600', '800', '1,200', '1,600'], 'D',
    'Nine years is three doubling periods, so the population is multiplied by 2 three times: 200 · 2 · 2 · 2 = 200 · 8 = 1,600. Choice A multiplies by 3 rather than doubling three times.'),
  mc('adv-46', NLF, 'Medium', 'In which direction does the graph of y = −x² open?',
    ['Upward', 'Downward', 'It is a straight line', 'It is a circle'], 'B',
    'The coefficient of x² is negative, so the parabola opens downward. A positive coefficient would open upward.'),
  spr('adv-47', NLF, 'Hard', 'The function f is defined by f(x) = x² − 4x + 7. What is the minimum value of f?', ['3'],
    'The parabola opens upward, so its minimum is at the vertex, where x = −b/(2a) = 4/2 = 2. Then f(2) = 4 − 8 + 7 = 3.'),
  mc('adv-48', NLF, 'Medium', 'The function f is defined by f(x) = x³. What is the value of f(−2)?',
    ['−8', '−6', '6', '8'], 'A',
    'Cubing a negative number gives a negative result: (−2)(−2)(−2) = −8. Choice D is the result of squaring instead of cubing.'),
  mc('adv-49', NLF, 'Hard', 'What is the equation of the axis of symmetry of the graph of y = (x + 1)(x − 5)?',
    ['x = −2', 'x = 1', 'x = 2', 'x = 3'], 'C',
    'The x-intercepts are at x = −1 and x = 5, and the axis of symmetry lies exactly halfway between them: (−1 + 5)/2 = 2.'),
  mc('adv-50', NLF, 'Medium', 'The value of a machine after x years is modeled by f(x) = 500(0.8)ˣ dollars. What was the value of the machine when it was new?',
    ['0', '0.8', '400', '500'], 'D',
    'A machine is new when x = 0, and (0.8)⁰ = 1, so f(0) = 500. Choice C is the value after one year.'),
];
