// 50 original Geometry and Trigonometry questions, written for this app rather than taken from the College
// Board bank, so they can ship in the repo and reach every visitor.
//
// Thirteen each on area and volume and on lines, angles and triangles, twelve each on right triangles and
// on circles. Answers involving π are asked as "the area is kπ, what is k?" so that a student-produced
// response stays a plain number and can be checked exactly rather than to a rounded decimal.
//
// Every answer is re-derived from the problem statement in tests/questions.test.js.

const DOMAIN = 'Geometry and Trigonometry';

const mc = (id, skill, difficulty, stem, choices, answer, rationale) => ({
  id: `og-${id}`, section: 'MATH', domain: DOMAIN, skill, difficulty, stem,
  choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })),
  answer, rationale, source: 'original',
});

const spr = (id, skill, difficulty, stem, answer, rationale) => ({
  id: `og-${id}`, section: 'MATH', domain: DOMAIN, skill, difficulty, stem,
  choices: null, answer, rationale, source: 'original',
});

const AV = 'Area and volume';
const LAT = 'Lines, angles, and triangles';
const RT = 'Right triangles and trigonometry';
const CIR = 'Circles';

export const GEOMETRY_QUESTIONS = [
  // ---- Area and volume ----
  mc('geo-01', AV, 'Easy', 'A rectangle has a length of 9 and a width of 4. What is its area?',
    ['13', '26', '36', '81'], 'C',
    'Area is length times width: 9 × 4 = 36. Choice B is the perimeter and choice A is the sum of the two dimensions.'),
  spr('geo-02', AV, 'Easy', 'A triangle has a base of 10 and a height of 6. What is its area?', ['30'],
    'The area of a triangle is half the base times the height: (1/2)(10)(6) = 30.'),
  mc('geo-03', AV, 'Medium', 'A circle has a radius of 5. What is its area?',
    ['5π', '10π', '25π', '50π'], 'C',
    'The area of a circle is πr², so with r = 5 the area is 25π. Choice B is the circumference, which uses 2πr.'),
  mc('geo-04', AV, 'Medium', 'A rectangular prism measures 3 by 4 by 5. What is its volume?',
    ['12', '47', '60', '94'], 'C',
    'Volume is the product of the three dimensions: 3 × 4 × 5 = 60. Choice D is the surface area.'),
  spr('geo-05', AV, 'Medium', 'A cylinder has a radius of 3 and a height of 10. Its volume is kπ cubic units. What is the value of k?', ['90'],
    'The volume of a cylinder is πr²h, so it is π(3²)(10) = 90π, giving k = 90.'),
  mc('geo-06', AV, 'Hard', 'A cube has a volume of 64. What is its surface area?',
    ['16', '48', '96', '384'], 'C',
    'Each edge is the cube root of 64, which is 4. A cube has 6 square faces, so the surface area is 6 × 4² = 96.'),
  mc('geo-07', AV, 'Medium', 'A square has an area of 49. What is its perimeter?',
    ['14', '28', '49', '196'], 'B',
    'Each side is √49 = 7, and a square has four equal sides, so the perimeter is 4 × 7 = 28.'),
  spr('geo-08', AV, 'Medium', 'A trapezoid has parallel sides of length 6 and 10 and a height of 4. What is its area?', ['32'],
    'The area of a trapezoid is the average of the parallel sides times the height: ((6 + 10)/2)(4) = 8 × 4 = 32.'),
  spr('geo-09', AV, 'Hard', 'A sphere has a radius of 3. Its volume is kπ cubic units. What is the value of k?', ['36'],
    'The volume of a sphere is (4/3)πr³, so it is (4/3)π(27) = 36π, giving k = 36.'),
  mc('geo-10', AV, 'Medium', 'A parallelogram has a base of 12 and a height of 5. What is its area?',
    ['17', '30', '60', '120'], 'C',
    'The area of a parallelogram is base times height: 12 × 5 = 60. Choice B halves it, which would be the formula for a triangle.'),
  mc('geo-11', AV, 'Hard', 'A rectangle has a perimeter of 36, and its length is twice its width. What is its area?',
    ['36', '54', '72', '108'], 'C',
    'If the width is w, the length is 2w and the perimeter is 2(w + 2w) = 6w = 36, so w = 6 and the length is 12. The area is 6 × 12 = 72.'),
  spr('geo-12', AV, 'Medium', 'A cone has a radius of 3 and a height of 4. Its volume is kπ cubic units. What is the value of k?', ['12'],
    'The volume of a cone is (1/3)πr²h, so it is (1/3)π(9)(4) = 12π, giving k = 12.'),
  mc('geo-13', AV, 'Hard', 'A rectangular prism has a volume of 120 and a base area of 24. What is its height?',
    ['4', '5', '6', '8'], 'B',
    'Volume equals base area times height, so the height is 120 ÷ 24 = 5.'),

  // ---- Lines, angles, and triangles ----
  mc('geo-14', LAT, 'Easy', 'Two angles of a triangle measure 50° and 60°. What is the measure of the third angle?',
    ['60°', '70°', '80°', '110°'], 'B',
    'The angles of a triangle add to 180°, so the third is 180 − 50 − 60 = 70°. Choice D is the sum of the two given angles.'),
  spr('geo-15', LAT, 'Easy', 'Two angles are supplementary, and one measures 115°. What is the measure of the other, in degrees?', ['65'],
    'Supplementary angles add to 180°, so the other is 180 − 115 = 65°.'),
  mc('geo-16', LAT, 'Medium', 'Two angles are complementary, and one measures 37°. What is the measure of the other?',
    ['43°', '53°', '143°', '153°'], 'B',
    'Complementary angles add to 90°, so the other is 90 − 37 = 53°. Choice C uses 180° instead, which is for supplementary angles.'),
  mc('geo-17', LAT, 'Medium', 'An isosceles triangle has a vertex angle of 40°. What is the measure of each base angle?',
    ['40°', '70°', '100°', '140°'], 'B',
    'The two base angles are equal and together make up 180 − 40 = 140°, so each is 70°.'),
  spr('geo-18', LAT, 'Medium', 'In a triangle, an exterior angle is formed at one vertex. The two non-adjacent interior angles measure 45° and 65°. What is the measure of that exterior angle, in degrees?', ['110'],
    'An exterior angle equals the sum of the two remote interior angles: 45 + 65 = 110°.'),
  mc('geo-19', LAT, 'Hard', 'Two parallel lines are cut by a transversal. One interior angle measures 65°. What is the measure of the interior angle on the same side of the transversal?',
    ['65°', '90°', '115°', '125°'], 'C',
    'Interior angles on the same side of a transversal are supplementary when the lines are parallel, so the other is 180 − 65 = 115°. Choice A would be the alternate interior angle.'),
  mc('geo-20', LAT, 'Medium', 'A triangle has sides of length 3, 4 and 5. What kind of triangle is it?',
    ['Acute', 'Obtuse', 'Not a valid triangle', 'Right'], 'D',
    'Since 3² + 4² = 9 + 16 = 25 = 5², the Pythagorean theorem holds exactly, so the triangle has a right angle.'),
  spr('geo-21', LAT, 'Medium', 'What is the sum of the interior angles of a pentagon, in degrees?', ['540'],
    'The interior angles of a polygon with n sides add to (n − 2)(180°). For a pentagon that is (5 − 2)(180) = 540°.'),
  mc('geo-22', LAT, 'Hard', 'Two similar triangles have corresponding sides in the ratio 2 to 3. A side of the smaller triangle has length 8. What is the length of the corresponding side of the larger triangle?',
    ['10', '12', '16', '24'], 'B',
    'Corresponding sides are proportional, so 8/x = 2/3 and x = 8 × 3/2 = 12. Choice D multiplies by 3 without dividing by 2.'),
  mc('geo-23', LAT, 'Medium', 'Two lines intersect. What is true of a pair of vertical angles?',
    ['They are complementary', 'They are supplementary', 'They are always right angles', 'They are equal in measure'], 'D',
    'Vertical angles are the pair opposite each other where two lines cross, and they always have equal measure. They are right angles only in the special case of perpendicular lines.'),
  mc('geo-24', LAT, 'Hard', 'A triangle has two sides of length 5 and 12. Which length could NOT be the third side?',
    ['8', '10', '16', '18'], 'D',
    'The third side must be greater than 12 − 5 = 7 and less than 12 + 5 = 17. Since 18 is not less than 17, it cannot form a triangle.'),
  spr('geo-25', LAT, 'Medium', 'What is the measure of each interior angle of a regular hexagon, in degrees?', ['120'],
    'The interior angles add to (6 − 2)(180) = 720°, and in a regular hexagon all six are equal, so each is 720 ÷ 6 = 120°.'),
  mc('geo-26', LAT, 'Hard', 'The three angles of a triangle are in the ratio 1 to 2 to 3. What is the measure of the largest angle?',
    ['30°', '60°', '90°', '120°'], 'C',
    'The ratio has 1 + 2 + 3 = 6 parts covering 180°, so each part is 30°. The largest angle is 3 parts, or 90°.'),

  // ---- Right triangles and trigonometry ----
  mc('geo-27', RT, 'Easy', 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?',
    ['10', '12', '14', '48'], 'A',
    'By the Pythagorean theorem the hypotenuse is √(6² + 8²) = √100 = 10. Choice C adds the legs instead.'),
  spr('geo-28', RT, 'Easy', 'A right triangle has a hypotenuse of 13 and one leg of 5. What is the length of the other leg?', ['12'],
    'Rearranging the Pythagorean theorem gives √(13² − 5²) = √(169 − 25) = √144 = 12.'),
  mc('geo-29', RT, 'Medium', 'In a right triangle, the side opposite angle A has length 3 and the hypotenuse has length 5. What is sin A?',
    ['3/5', '4/5', '3/4', '5/3'], 'A',
    'Sine is the opposite side over the hypotenuse, so sin A = 3/5. Choice B is the cosine and choice C is the tangent.'),
  mc('geo-30', RT, 'Medium', 'In a right triangle, the side adjacent to angle A has length 8 and the hypotenuse has length 17. What is cos A?',
    ['8/17', '15/17', '8/15', '17/8'], 'A',
    'Cosine is the adjacent side over the hypotenuse, so cos A = 8/17. Choice B is the sine, since the remaining leg is 15.'),
  spr('geo-31', RT, 'Medium', 'In a right triangle, the side opposite angle A has length 7 and the side adjacent to angle A has length 24. What is tan A?', ['7/24'],
    'Tangent is the opposite side over the adjacent side, so tan A = 7/24.'),
  mc('geo-32', RT, 'Hard', 'In a 30°-60°-90° triangle, the shorter leg has length 5. What is the length of the hypotenuse?',
    ['5√3', '10', '10√3', '15'], 'B',
    'In a 30°-60°-90° triangle the sides are in the ratio x, x√3, 2x, with the shorter leg opposite the 30° angle. The hypotenuse is twice the shorter leg, so it is 10. Choice A is the longer leg.'),
  mc('geo-33', RT, 'Hard', 'In a 45°-45°-90° triangle, each leg has length 6. What is the length of the hypotenuse?',
    ['6', '6√2', '12', '12√2'], 'B',
    'In a 45°-45°-90° triangle the sides are in the ratio s, s, s√2, so the hypotenuse is 6√2.'),
  mc('geo-34', RT, 'Medium', 'In a right triangle, A and B are the two acute angles and sin A = 0.6. What is cos B?',
    ['0.4', '0.6', '0.8', '1.0'], 'B',
    'The two acute angles of a right triangle add to 90°, and the cosine of an angle equals the sine of its complement. So cos B = sin A = 0.6.'),
  spr('geo-35', RT, 'Hard', 'A right triangle has legs of length 9 and 12. What is its area?', ['54'],
    'The two legs are perpendicular, so they serve as base and height: (1/2)(9)(12) = 54.'),
  mc('geo-36', RT, 'Medium', 'A right triangle has a hypotenuse of length 10, and one acute angle measures 30°. What is the length of the side opposite that angle?',
    ['5', '5√3', '8.66', '10'], 'A',
    'The opposite side is the hypotenuse times the sine of the angle: 10 × sin 30° = 10 × 0.5 = 5. Choice B is the side adjacent to the 30° angle.'),
  mc('geo-37', RT, 'Hard', 'For any angle θ, what does sin²θ + cos²θ equal?',
    ['0', '1', '2', 'θ'], 'B',
    'This is the Pythagorean identity. On a unit circle the two legs are cos θ and sin θ and the hypotenuse is 1, so sin²θ + cos²θ = 1 for every angle.'),
  spr('geo-38', RT, 'Medium', 'A right triangle has legs of length 15 and 20. What is the length of the hypotenuse?', ['25'],
    'By the Pythagorean theorem the hypotenuse is √(15² + 20²) = √(225 + 400) = √625 = 25.'),

  // ---- Circles ----
  spr('geo-39', CIR, 'Easy', 'A circle has a radius of 7. Its circumference is kπ units. What is the value of k?', ['14'],
    'The circumference of a circle is 2πr, so it is 2π(7) = 14π, giving k = 14.'),
  mc('geo-40', CIR, 'Easy', 'A circle has a diameter of 10. What is its area?',
    ['5π', '10π', '25π', '100π'], 'C',
    'The radius is half the diameter, so r = 5, and the area is πr² = 25π. Choice D squares the diameter instead of the radius.'),
  mc('geo-41', CIR, 'Medium', 'A circle in the xy-plane has the equation (x − 2)² + (y + 1)² = 49. What is its radius?',
    ['7', '14', '24.5', '49'], 'A',
    'In the form (x − h)² + (y − k)² = r², the right side is r². Here r² = 49, so r = 7. Choice D mistakes r² for r.'),
  spr('geo-42', CIR, 'Medium', 'A circle in the xy-plane has the equation (x − 3)² + (y − 4)² = 25. What is the x-coordinate of its center?', ['3'],
    'In the form (x − h)² + (y − k)² = r², the center is (h, k). Here the expression is (x − 3)², so h = 3.'),
  spr('geo-43', CIR, 'Medium', 'A circle has a radius of 4. An arc of the circle is cut off by a central angle of 90°. The arc length is kπ units. What is the value of k?', ['2'],
    'A 90° angle is a quarter of the full 360°, so the arc is a quarter of the circumference: (1/4)(2π)(4) = 2π, giving k = 2.'),
  spr('geo-44', CIR, 'Hard', 'A circle has a radius of 6. A sector is cut off by a central angle of 60°. The area of the sector is kπ square units. What is the value of k?', ['6'],
    'A 60° angle is one sixth of 360°, so the sector is one sixth of the area: (1/6)π(36) = 6π, giving k = 6.'),
  mc('geo-45', CIR, 'Medium', 'An inscribed angle and a central angle intercept the same arc of a circle. How are their measures related?',
    ['They are equal', 'The inscribed angle is twice the central angle', 'They are supplementary', 'The inscribed angle is half the central angle'], 'D',
    'The inscribed angle theorem says an inscribed angle measures half the central angle that intercepts the same arc.'),
  mc('geo-46', CIR, 'Hard', 'A circle in the xy-plane has the equation x² + y² = 36. What is its radius?',
    ['6', '12', '18', '36'], 'A',
    'The equation is centered at the origin with r² = 36, so the radius is √36 = 6. Choice B is the diameter.'),
  mc('geo-47', CIR, 'Medium', 'A circle has a circumference of 20π. What is its radius?',
    ['5', '10', '20', '40'], 'B',
    'Circumference is 2πr, so 2πr = 20π gives r = 10. Choice C mistakes the coefficient for the radius.'),
  spr('geo-48', CIR, 'Hard', 'A circle has an area of 36π square units. What is its radius?', ['6'],
    'Area is πr², so πr² = 36π gives r² = 36 and r = 6.'),
  mc('geo-49', CIR, 'Medium', 'How many degrees of arc does a full circle contain?',
    ['90', '180', '270', '360'], 'D',
    'A full turn around a circle is 360°. Choice B is a semicircle.'),
  mc('geo-50', CIR, 'Hard', 'An angle measures π/3 radians. What is its measure in degrees?',
    ['30°', '45°', '60°', '90°'], 'C',
    'A full circle is 2π radians or 360°, so π radians is 180°. Therefore π/3 radians is 180 ÷ 3 = 60°.'),
];
