// 60 original MCAT questions for Psychological, Social, and Biological Foundations of Behavior, written for this app:
// the AAMC publishes no question bank, and its practice material may not be copied.
//
// Five per content category. The section has twelve categories, so the tiers are spread across them in three
// patterns (two Foundation, two Intermediate and one Exam-level; two, one and two; one, two and two), giving twenty
// at each tier. The correct letters were planned before writing, fifteen of each. These are stand-alone
// questions; the passage sets are in js/questions/mcat-ps-passages.js. The few calculated answers are worked out
// again in tests/mcat-questions.test.js.

const DOMAIN = {
  6: 'Sensing and processing (Foundational Concept 6)',
  7: 'Individual behavior (Foundational Concept 7)',
  8: 'Self and others (Foundational Concept 8)',
  9: 'Social structure and demographics (Foundational Concept 9)',
  10: 'Social inequality (Foundational Concept 10)',
};
const SKILL = {
  '6A': '6A: Sensing the environment',
  '6B': '6B: Making sense of the environment',
  '6C': '6C: Responding to the world',
  '7A': '7A: Individual influences on behavior',
  '7B': '7B: Social processes that influence human behavior',
  '7C': '7C: Attitude and behavior change',
  '8A': '8A: Self-identity',
  '8B': '8B: Social thinking',
  '8C': '8C: Social interactions',
  '9A': '9A: Understanding social structure',
  '9B': '9B: Demographic characteristics and processes',
  '10A': '10A: Social inequality',
};

const mc = (id, code, difficulty, stem, choices, answer, rationale) => ({
  id: `mcat-ps-${id}`, exam: 'mcat', section: 'PS', domain: DOMAIN[parseInt(code, 10)], skill: SKILL[code],
  difficulty, stem, choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })), answer, rationale, source: 'original',
});

export const MCAT_PS_QUESTIONS = [
  // ---- 6A: sensing the environment ----
  mc('6a-1', '6A', 'Easy', 'The weakest stimulus that a person can detect half of the time is called the:',
    ['difference threshold', 'just-noticeable difference', 'absolute threshold', 'signal-to-noise ratio'], 'C',
    'The absolute threshold is the minimum stimulus intensity detected 50% of the time. The difference threshold, or just-noticeable difference, is instead the smallest change in a stimulus that can be detected.'),
  mc('6a-2', '6A', 'Easy', 'Which cells in the retina make color vision possible in bright light?',
    ['Cones', 'Rods', 'Bipolar cells', 'Ganglion cells'], 'A',
    'Cones, concentrated in the fovea, come in three types sensitive to different wavelengths, which is what allows color vision; they need bright light. Rods are far more sensitive and handle dim light but cannot tell colors apart. Bipolar and ganglion cells pass the signals on toward the brain.'),
  mc('6a-3', '6A', 'Medium', 'A person can just tell a 105 g weight from a 100 g one. According to Weber’s law, what is the smallest difference they could detect from a 400 g weight?',
    ['5 g', '10 g', '15 g', '20 g'], 'D',
    'Weber’s law says the just-noticeable difference is a constant fraction of the original stimulus. Here that fraction is 5 g ÷ 100 g = 0.05, so for 400 g it is 0.05 × 400 = 20 g. Assuming the difference stays at 5 g ignores the law.'),
  mc('6a-4', '6A', 'Medium', 'In signal detection theory, a radiologist who reports a tumor that is not there has made a:',
    ['hit', 'false alarm', 'miss', 'correct rejection'], 'B',
    'Signal detection theory crosses whether a signal is present with whether it is reported. Reporting a signal that is absent is a false alarm; reporting one that is present is a hit; failing to report one that is present is a miss; and correctly reporting none is a correct rejection.'),
  mc('6a-5', '6A', 'Hard', 'A stroke damages a patient’s primary visual cortex in the left occipital lobe. Which part of the visual field is most likely lost?',
    ['The right half of the visual field, in both eyes', 'The left half of the visual field, in each of the two eyes', 'All vision in the left eye', 'The outer half of each eye’s visual field'], 'A',
    'At the optic chiasm, fibers from the inner half of each retina cross, so each hemisphere receives the opposite half of the visual field from both eyes. Damage to the left visual cortex therefore removes the right half of the field in both eyes. Losing all vision in one eye points to that eye or its optic nerve, and losing the outer halves points to the chiasm itself.'),

  // ---- 6B: making sense of the environment ----
  mc('6b-1', '6B', 'Easy', 'In Piaget’s theory, a child who understands that water poured from a short, wide glass into a tall, thin one is still the same amount has achieved:',
    ['object permanence', 'conservation', 'abstract reasoning', 'egocentrism'], 'B',
    'Conservation, the understanding that quantity stays the same when appearance changes, marks Piaget’s concrete operational stage, from about age 7. Object permanence arrives in the sensorimotor stage, abstract reasoning in the formal operational stage, and egocentrism is a limitation of the preoperational stage.'),
  mc('6b-2', '6B', 'Easy', 'Which stage of sleep is most associated with vivid dreaming and near-paralysis of the skeletal muscles?',
    ['Stage N1', 'Stage N2', 'Stage N3 (slow-wave sleep)', 'REM sleep'], 'D',
    'In REM sleep the brain’s activity resembles waking, most vivid dreams occur, and the skeletal muscles are almost paralyzed. N1 is light sleep, N2 brings sleep spindles and K-complexes, and N3 is deep, slow-wave sleep.'),
  mc('6b-3', '6B', 'Medium', 'Students who learn a word list in one room recall more of it when tested in that room than in a different one. This is an example of:',
    ['context-dependent memory', 'state-dependent memory', 'the serial position effect', 'proactive interference'], 'A',
    'Recall is better when the external surroundings at retrieval match those at learning: context-dependent memory. State-dependent memory is the same effect for an internal state, such as mood or intoxication. The serial position effect concerns where items fall in a list, and proactive interference is old learning disrupting new.'),
  mc('6b-4', '6B', 'Hard', 'A patient with damage to Wernicke’s area would most likely:',
    ['speak haltingly, in short phrases, but understand speech well', 'speak fluently and understand well but be unable to repeat phrases',
      'speak fluently but with little meaning, and have trouble understanding others', 'lose the ability to read while still being able to write'], 'C',
    'Wernicke’s area, in the temporal lobe, supports language comprehension, so damage produces fluent but largely meaningless speech and poor understanding. Halting speech with good comprehension describes Broca’s aphasia, and an inability to repeat with fluent speech and good comprehension describes conduction aphasia, from damage to the arcuate fasciculus.'),
  mc('6b-5', '6B', 'Hard', 'A doctor who has just treated three patients with a rare infection overestimates the chance that the next patient with a fever has it. This reflects the:',
    ['representativeness heuristic', 'confirmation bias', 'belief perseverance', 'availability heuristic'], 'D',
    'The availability heuristic judges likelihood by how easily examples come to mind, and recent, vivid cases come to mind easily. The representativeness heuristic judges by how well a case matches a prototype, confirmation bias is seeking evidence for what one already believes, and belief perseverance is holding a belief after its basis is discredited.'),

  // ---- 6C: responding to the world ----
  mc('6c-1', '6C', 'Easy', 'Which brain structure is most closely linked to processing fear?',
    ['Hippocampus', 'Cerebellum', 'Thalamus', 'Amygdala'], 'D',
    'The amygdala, part of the limbic system, detects threats and drives fear responses and fear learning. The hippocampus forms new explicit memories, the cerebellum coordinates movement, and the thalamus relays sensory information.'),
  mc('6c-2', '6C', 'Easy', 'According to the James–Lange theory of emotion, a person who meets a bear on a trail:',
    ['feels afraid and starts trembling at the same moment', 'feels afraid, and the fear then makes them tremble',
      'trembles, and their awareness of trembling is the feeling of fear', 'labels their racing heart as fear because they know a bear is present'], 'C',
    'James and Lange held that the body’s response comes first and the emotion is the experience of that response. Simultaneous fear and arousal is the Cannon–Bard theory, and labeling arousal by its context is the Schachter–Singer two-factor theory.'),
  mc('6c-3', '6C', 'Medium', 'In Selye’s general adaptation syndrome, the stage in which the body’s resources are worn down by long-lasting stress is:',
    ['alarm', 'exhaustion', 'resistance', 'recovery'], 'B',
    'The general adaptation syndrome has three stages: alarm (the initial fight-or-flight response), resistance (sustained coping, with stress hormones raised) and exhaustion, when resources run out and illness becomes more likely. Recovery is not one of Selye’s stages.'),
  mc('6c-4', '6C', 'Medium', 'In Lazarus’s appraisal theory of stress, judging whether one has the resources to cope with a threat is called:',
    ['secondary appraisal', 'primary appraisal', 'reappraisal', 'cognitive restructuring'], 'A',
    'Primary appraisal asks whether a situation is irrelevant, benign or threatening; secondary appraisal asks whether one can cope with it. Reappraisal is revising those judgments later, and cognitive restructuring is a therapy technique for changing patterns of thought, not a stage of the theory.'),
  mc('6c-5', '6C', 'Hard', 'In Schachter and Singer’s study, participants injected with epinephrine and not told about its effects most often:',
    ['felt no emotion, since their arousal was produced by a drug', 'reported the same emotion whatever the other person in the room did',
      'took on the emotion of a confederate, whether euphoria or anger', 'felt calm, because they expected the injection to have side effects'], 'C',
    'Uninformed participants had arousal they could not explain, so they labeled it using the situation, matching the euphoric or angry confederate. Informed participants, who could put their arousal down to the drug, were less affected. This supports the two-factor theory: emotion is arousal plus a cognitive label.'),

  // ---- 7A: individual influences on behavior ----
  mc('7a-1', '7A', 'Easy', 'Which of the Big Five personality traits describes a tendency toward anxiety, moodiness and emotional instability?',
    ['Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness'], 'A',
    'Neuroticism is the tendency to experience negative emotions and emotional instability. Openness concerns curiosity and imagination, agreeableness warmth and cooperation, and conscientiousness organization and self-discipline. The fifth trait is extraversion.'),
  mc('7a-2', '7A', 'Easy', 'Identical twins raised apart resemble each other on a trait more than fraternal twins raised apart do. This most directly suggests that the trait is:',
    ['mostly learned from one’s parents', 'partly heritable', 'decided by birth order', 'shaped only by a shared environment'], 'B',
    'Twins raised apart share no family environment, so their similarity reflects shared genes (and, for identical twins, a shared prenatal environment). Identical twins share all their genes and fraternal twins about half, so greater similarity among identical twins points to a genetic contribution. It does not show the trait is entirely genetic.'),
  mc('7a-3', '7A', 'Medium', 'The Yerkes–Dodson law states that performance:',
    ['rises steadily as arousal rises', 'falls steadily as arousal rises',
      'peaks at a moderate level of arousal', 'depends only on the reward offered for it'], 'C',
    'Performance follows an inverted U: too little arousal and people are unmotivated, too much and they become anxious and disorganized. The best level of arousal is lower for difficult or unfamiliar tasks and higher for simple, well-practiced ones.'),
  mc('7a-4', '7A', 'Hard', 'Volunteers paid $1 to tell others that a boring task was fun later rated the task as more enjoyable than volunteers paid $20 to do the same. This is best explained by:',
    ['drive-reduction theory', 'the overjustification effect', 'social facilitation', 'cognitive dissonance'], 'D',
    'Saying the task was fun conflicted with finding it boring. The $20 group could explain the lie by the payment, but $1 was too little to justify it, so that group reduced the dissonance by coming to see the task as more enjoyable. The overjustification effect is the reverse situation, in which a reward undermines an activity people already enjoyed.'),
  mc('7a-5', '7A', 'Hard', 'According to the diathesis–stress model, a psychological disorder develops when:',
    ['a traumatic event occurs, whatever the person’s genes, history or temperament', 'a biological or genetic vulnerability meets environmental stress',
      'levels of neurotransmitters change with age', 'a person copies harmful behavior modeled by parents or peers'], 'B',
    'The model holds that neither vulnerability nor stress alone is usually enough: a predisposition (the diathesis) leads to a disorder when life stress is great enough. This explains why only some people exposed to the same stressor develop a disorder.'),

  // ---- 7B: social processes that influence behavior ----
  mc('7b-1', '7B', 'Easy', 'In Asch’s line-judgment experiments, many participants gave obviously wrong answers when the rest of the group did. This demonstrates:',
    ['obedience', 'group polarization', 'conformity', 'social loafing'], 'C',
    'Conformity is changing one’s behavior or judgment to match a group. Obedience is following the orders of an authority, as in Milgram’s studies; group polarization is a group’s views becoming more extreme; and social loafing is reduced effort in a group.'),
  mc('7b-2', '7B', 'Easy', 'When individual contributions cannot be identified, people tend to put less effort into a group task than into the same task alone. This is called:',
    ['social facilitation', 'deindividuation', 'groupthink', 'social loafing'], 'D',
    'Social loafing is reduced effort when one’s own contribution is hidden within a group’s. Social facilitation is better performance of simple tasks in front of others, deindividuation is a loss of self-awareness in crowds, and groupthink is a group’s drive for agreement overriding good judgment.'),
  mc('7b-3', '7B', 'Medium', 'According to research on the bystander effect, a person who collapses on a busy street is:',
    ['less likely to be helped by any one onlooker than by a lone witness', 'more likely to be helped, because more people see the emergency',
      'equally likely to be helped however many people happen to be present', 'likely to be helped only by people who know them'], 'A',
    'With more onlookers, each feels less personally responsible (diffusion of responsibility) and takes others’ inaction as a sign that nothing is wrong. So each individual is less likely to help, and help often comes later, than when a single witness is present.'),
  mc('7b-4', '7B', 'Medium', 'In Milgram’s studies of obedience, the rate of obedience fell most sharply when:',
    ['the experimenter wore a gray lab coat', 'the experimenter gave the orders by telephone from another room',
      'the study was run in the laboratories of a prestigious university', 'the learner could be heard but not seen'], 'B',
    'Obedience depended heavily on the authority’s presence: when the experimenter left and gave orders by telephone, far fewer participants continued to the end. The lab coat and the university setting increased the experimenter’s authority, and a learner heard but not seen was the standard arrangement in which most participants obeyed.'),
  mc('7b-5', '7B', 'Hard', 'A close-knit committee, eager to stay in agreement, approves a flawed plan without weighing alternatives, and members keep their doubts to themselves. This best illustrates:',
    ['group polarization', 'social loafing', 'deindividuation', 'groupthink'], 'D',
    'Groupthink is a cohesive group’s desire for harmony overriding realistic judgment: dissent is suppressed and alternatives are not considered. Group polarization is different: discussion pushes a group’s existing views to a more extreme position, rather than silencing doubts.'),

  // ---- 7C: attitude and behavior change ----
  mc('7c-1', '7C', 'Easy', 'In Pavlov’s experiments, a dog’s salivation at the sound of a bell after training is the:',
    ['unconditioned response', 'conditioned response', 'unconditioned stimulus', 'neutral stimulus'], 'B',
    'Salivating to food is the unconditioned response to an unconditioned stimulus. After the bell is repeatedly paired with food, the bell becomes a conditioned stimulus, and salivating to it is the conditioned response. Before training the bell was a neutral stimulus.'),
  mc('7c-2', '7C', 'Medium', 'A parent takes away a teenager’s phone to reduce late-night texting. This is an example of:',
    ['negative punishment', 'positive punishment', 'negative reinforcement', 'extinction'], 'A',
    'Punishment aims to reduce a behavior, and “negative” means something is taken away: removing the phone is negative punishment. Positive punishment adds something unpleasant, negative reinforcement removes something unpleasant to increase a behavior, and extinction is withholding the reward that kept a behavior going.'),
  mc('7c-3', '7C', 'Medium', 'A slot machine pays out after an unpredictable number of plays. Which schedule of reinforcement is this, and what pattern of behavior does it produce?',
    ['Fixed interval; responding that speeds up as each payout time approaches', 'Fixed ratio; a pause after each payout, then fast responding',
      'Variable interval; slow, steady responding', 'Variable ratio; fast, steady responding that is hard to extinguish'], 'D',
    'Reinforcement after an unpredictable number of responses is a variable-ratio schedule. Since any response might be the one that pays, it produces high, steady responding that persists long after the rewards stop. The other patterns belong to the schedules they are paired with.'),
  mc('7c-4', '7C', 'Hard', 'In Bandura’s Bobo doll studies, children who watched an adult attack the doll and then saw the adult punished later:',
    ['never attacked the doll, even when offered rewards for doing so', 'attacked the doll more than children who saw the adult rewarded',
      'imitated less at first, but reproduced the attacks when offered a reward', 'behaved no differently from children who had not watched any adult at all'], 'C',
    'Seeing the model punished reduced imitation at first, but when the children were later offered rewards to copy the model, they reproduced the aggression as well as the other groups. They had learned the behavior all along: observational learning can occur without being shown in performance.'),
  mc('7c-5', '7C', 'Hard', 'According to the elaboration likelihood model, a tired viewer with little interest in a product is most likely to be persuaded by:',
    ['a celebrity’s endorsement, through the peripheral route', 'detailed evidence of the product’s quality, through the central route',
      'a long, carefully reasoned case for the product', 'statistics comparing the product with its competitors'], 'A',
    'People who are unable or unmotivated to think carefully rely on the peripheral route: surface cues such as an attractive or famous source. Strong arguments, detailed evidence and statistics persuade through the central route, which needs motivation and attention. Change through the central route tends to last longer.'),

  // ---- 8A: self-identity ----
  mc('8a-1', '8A', 'Easy', 'A person’s belief in their ability to succeed at a particular task is called:',
    ['self-esteem', 'self-concept', 'locus of control', 'self-efficacy'], 'D',
    'Self-efficacy, Bandura’s term, is confidence in one’s ability to carry out a specific task. Self-esteem is one’s overall sense of worth, self-concept is the whole set of beliefs about oneself, and locus of control is the belief about whether outcomes depend on oneself or on outside forces.'),
  mc('8a-2', '8A', 'Easy', 'According to Erikson, the central conflict of adolescence is:',
    ['trust versus mistrust', 'intimacy versus isolation', 'identity versus role confusion', 'industry versus inferiority'], 'C',
    'In Erikson’s eight stages, adolescence centers on forming a stable identity. Trust versus mistrust belongs to infancy, industry versus inferiority to the school years, and intimacy versus isolation to young adulthood.'),
  mc('8a-3', '8A', 'Medium', 'A student believes that his grades depend mostly on luck and on his teachers rather than on his own effort. He has:',
    ['an internal locus of control', 'an external locus of control', 'high self-efficacy', 'a strong gender schema'], 'B',
    'Locus of control is where a person believes the causes of outcomes lie. Crediting luck and other people places them outside oneself, an external locus. Someone with an internal locus would see his grades as the result of his own effort.'),
  mc('8a-4', '8A', 'Medium', 'In Kohlberg’s theory, a person who obeys laws mainly to keep social order is at which level of moral reasoning?',
    ['Conventional', 'Preconventional', 'Postconventional', 'Formal operational'], 'A',
    'Kohlberg’s conventional level bases morality on social approval and on law and order. The preconventional level is based on avoiding punishment and gaining rewards, and the postconventional level on social contracts and universal ethical principles. Formal operational is one of Piaget’s stages, not Kohlberg’s.'),
  mc('8a-5', '8A', 'Hard', 'George Herbert Mead distinguished two parts of the self, the “I” and the “me.” The “me” is:',
    ['the spontaneous, impulsive part of the self that acts in the moment', 'the part of the self that lies outside awareness',
      'the self as seen through the internalized attitudes of others', 'the self’s biological drives and needs'], 'C',
    'For Mead, the “me” is the social self, formed by taking the perspective of others and internalizing society’s expectations (the “generalized other”), while the “I” is the spontaneous, acting self that responds to them. Neither is defined by the unconscious or by biological drives.'),

  // ---- 8B: social thinking ----
  mc('8b-1', '8B', 'Easy', 'Blaming another driver’s cutting in on rudeness, while blaming your own cutting in on being late, is an example of:',
    ['the actor–observer bias', 'the halo effect', 'stereotype threat', 'the just-world hypothesis'], 'A',
    'The actor–observer bias is explaining others’ behavior by their character but one’s own by the situation. The halo effect is letting one good trait color judgments of others, stereotype threat is anxiety about confirming a stereotype, and the just-world hypothesis is the belief that people get what they deserve.'),
  mc('8b-2', '8B', 'Easy', 'Judging other cultures by the standards of one’s own is called:',
    ['cultural relativism', 'assimilation', 'culture shock', 'ethnocentrism'], 'D',
    'Ethnocentrism treats one’s own culture as the standard for judging others. Cultural relativism is the opposite: judging a culture on its own terms. Assimilation is a minority group taking on the dominant culture, and culture shock is the disorientation felt in an unfamiliar culture.'),
  mc('8b-3', '8B', 'Medium', 'Stereotype threat refers to:',
    ['holding a negative belief about another group', 'treating members of a group unfairly, in hiring or housing, because of their group',
      'underperforming out of worry about confirming a stereotype about one’s group', 'believing that one’s own group is better than others'], 'C',
    'Stereotype threat is the anxiety of possibly confirming a negative stereotype about one’s group, which can itself lower performance, for example on tests. A negative belief about a group is a stereotype or prejudice, unfair treatment is discrimination, and favoring one’s own group is in-group bias.'),
  mc('8b-4', '8B', 'Hard', 'A teacher expects a student to excel and gives her more attention and encouragement, and the student’s grades rise as a result. This illustrates:',
    ['stereotype threat', 'a self-fulfilling prophecy', 'the just-world hypothesis', 'the fundamental attribution error'], 'B',
    'In a self-fulfilling prophecy an expectation changes behavior in ways that make the expectation come true: the teacher’s belief led to treatment that raised the student’s performance. Stereotype threat lowers performance, and the just-world hypothesis and the fundamental attribution error are ways of explaining outcomes, not of producing them.'),
  mc('8b-5', '8B', 'Hard', 'The fundamental attribution error tends to be weaker in collectivist cultures than in individualist ones. Which explanation best fits this finding?',
    ['People in collectivist cultures know less about each other’s personalities.', 'People in collectivist cultures give more weight to the situation when explaining behavior.',
      'Collectivist cultures punish people who explain behavior by personality rather than circumstance.', 'People in collectivist cultures explain behavior less often.'], 'B',
    'The fundamental attribution error is overemphasizing personality and underestimating the situation in explaining others’ behavior. Collectivist cultures emphasize roles, relationships and context, so their members attend more to situational causes and show the error less.'),

  // ---- 8C: social interactions ----
  mc('8c-1', '8C', 'Easy', 'Erving Goffman’s dramaturgical approach compares social life to:',
    ['a market', 'a family', 'a theater performance', 'a machine'], 'C',
    'Goffman described people as actors managing the impressions they give: performing on a “front stage” before an audience and relaxing “backstage.” The approach is a form of symbolic interactionism, concerned with how people present themselves in everyday interaction.'),
  mc('8c-2', '8C', 'Medium', 'In Ainsworth’s Strange Situation, a child who is upset when the caregiver leaves and quickly comforted when the caregiver returns shows:',
    ['avoidant attachment', 'secure attachment', 'ambivalent (resistant) attachment', 'disorganized attachment'], 'B',
    'Securely attached children use the caregiver as a safe base, show distress at separation and are readily comforted at reunion. Avoidant children show little distress and ignore the caregiver on return, ambivalent children are distressed and hard to comfort, and disorganized children behave inconsistently.'),
  mc('8c-3', '8C', 'Medium', 'A surgeon who is also a parent misses her child’s school play because of an emergency operation. She is experiencing:',
    ['role exit', 'role strain', 'status inconsistency', 'role conflict'], 'D',
    'Role conflict is tension between the demands of two different roles, here surgeon and parent. Role strain is tension within a single role, role exit is leaving a role behind, and status inconsistency is holding statuses of very different rank.'),
  mc('8c-4', '8C', 'Hard', 'Which of the following is an example of institutional discrimination?',
    ['A firm hires only from areas where few people of one race live, whatever its intent', 'A manager refuses to hire an applicant because of her accent',
      'A person repeatedly avoids sitting next to people of another race on buses and in waiting rooms', 'A person believes that members of a group have less ability'], 'A',
    'Institutional discrimination is built into an organization’s policies and practices and produces unequal outcomes even without prejudiced intent. A manager acting on bias is individual discrimination, avoiding people is individual behavior, and a belief about a group’s ability is a stereotype.'),
  mc('8c-5', '8C', 'Hard', 'Robert Michels’s “iron law of oligarchy” holds that:',
    ['bureaucracies become more democratic as they grow', 'organizations should be run by trained experts',
      'large organizations become steadily less efficient as they grow older and bigger', 'even democratic organizations come to be run by a small group of leaders'], 'D',
    'Michels argued that the needs of organization concentrate power: leaders gain control of information and resources, so even organizations founded on democratic principles come to be ruled by a few. The claim is about who holds power, not about expertise or efficiency.'),

  // ---- 9A: understanding social structure ----
  mc('9a-1', '9A', 'Easy', 'Which sociological perspective views society as a system of parts that work together to keep it stable?',
    ['Conflict theory', 'Functionalism', 'Symbolic interactionism', 'Social constructionism'], 'B',
    'Functionalism, associated with Durkheim, sees each institution as serving a function that keeps society stable. Conflict theory stresses competition for scarce resources, symbolic interactionism focuses on meaning made in everyday interaction, and social constructionism on how shared understandings create social reality.'),
  mc('9a-2', '9A', 'Easy', 'Which theory focuses on how people create meaning through everyday interactions and shared symbols?',
    ['Symbolic interactionism', 'Functionalism', 'Conflict theory', 'Rational choice theory'], 'A',
    'Symbolic interactionism, associated with Mead and Blumer, studies how people act on the meanings things have for them, meanings built through interaction. It works at the micro level, while functionalism and conflict theory mainly analyze whole societies. Rational choice theory models behavior as weighing costs and benefits.'),
  mc('9a-3', '9A', 'Medium', 'Robert Merton distinguished manifest functions, which are intended, from latent functions, which are not. Which is a latent function of college?',
    ['Teaching students the skills they will need for their careers', 'Awarding degrees',
      'Serving as a place where students meet future partners', 'Preparing students for graduate school'], 'C',
    'Latent functions are unintended, often unrecognized consequences. Colleges are not set up to help students find partners, yet they do. Teaching skills, awarding degrees and preparing students for further study are among college’s intended, manifest functions.'),
  mc('9a-4', '9A', 'Hard', 'The period during which a culture’s norms and values catch up with a new technology is called:',
    ['culture shock', 'assimilation', 'diffusion', 'cultural lag'], 'D',
    'Cultural lag, William Ogburn’s term, is the gap between rapid change in material culture, such as technology, and slower change in nonmaterial culture, such as norms and laws. Diffusion is the spread of cultural traits between groups, and culture shock and assimilation concern individuals and groups meeting a new culture.'),
  mc('9a-5', '9A', 'Hard', 'A sociologist argues that race is a category that societies have created and given meaning to, rather than a natural biological division. This view reflects:',
    ['social constructionism', 'functionalism', 'rational choice theory', 'exchange theory'], 'A',
    'Social constructionism holds that many categories treated as natural are created and sustained by shared social understandings. Racial categories differ between societies and change over time, which supports this view. Functionalism, rational choice theory and exchange theory do not center on how categories are constructed.'),

  // ---- 9B: demographic characteristics and processes ----
  mc('9b-1', '9B', 'Easy', 'Which three processes directly change the size of a population?',
    ['Fertility, mortality and urbanization', 'Mortality, migration and globalization', 'Fertility, urbanization and aging', 'Fertility, mortality and migration'], 'D',
    'A population grows through births and immigration and shrinks through deaths and emigration, so fertility, mortality and migration are the three components of population change. Urbanization changes where people live, globalization changes how societies connect, and aging is a result of changes in the three components.'),
  mc('9b-2', '9B', 'Medium', 'A country’s population is growing by 2% a year. Using the rule of 70, about how long will it take to double?',
    ['2 years', '20 years', '35 years', '50 years'], 'C',
    'The rule of 70 estimates doubling time as 70 divided by the annual growth rate in percent: 70 ÷ 2 = 35 years. Dividing 100 by the rate would give 50 years, which ignores the compounding of growth.'),
  mc('9b-3', '9B', 'Medium', 'In the demographic transition model, the stage in which death rates have fallen but birth rates are still high is marked by:',
    ['rapid population growth', 'a shrinking population', 'a stable population with high birth and death rates', 'a stable population with low birth and death rates'], 'A',
    'In the second stage, better food, sanitation and medicine cut death rates while birth rates stay high, so the population grows rapidly. The first stage has high birth and death rates and a stable population; the last stages have low rates of both, and some populations then begin to shrink.'),
  mc('9b-4', '9B', 'Hard', 'A town has 30,000 people aged 15 to 64, 12,000 under 15, and 6,000 aged 65 or older. What is its total dependency ratio?',
    ['20', '40', '60', '167'], 'C',
    'The total dependency ratio compares people of dependent age with those of working age: (12,000 + 6,000) ÷ 30,000 × 100 = 60 dependents per 100 working-age people. 40 is the youth ratio alone, 20 the old-age ratio alone, and 167 turns the ratio upside down.'),
  mc('9b-5', '9B', 'Hard', 'A population pyramid with a wide base that narrows steadily toward the top most likely describes a country with:',
    ['low birth rates and long life expectancy', 'high birth rates and relatively short life expectancy',
      'a population that is shrinking and aging', 'a large wave of immigrants of working age'], 'B',
    'A wide base means many children, from high birth rates, and a steady narrowing means each older group is smaller, reflecting higher mortality and shorter lives. Low birth rates give a narrow base, an aging, shrinking population is top-heavy, and working-age immigration makes the middle bulge.'),

  // ---- 10A: social inequality ----
  mc('10a-1', '10A', 'Easy', 'A family whose income is too low to pay for basic food and shelter is living in:',
    ['absolute poverty', 'relative poverty', 'social exclusion', 'the culture of poverty'], 'A',
    'Absolute poverty is lacking the resources for basic necessities. Relative poverty is having much less than others in one’s society, even if basic needs are met. Social exclusion is being shut out of social participation, and the culture of poverty is a contested theory about values in poor communities.'),
  mc('10a-2', '10A', 'Medium', 'Pierre Bourdieu’s concept of cultural capital refers to:',
    ['money, property and other economic assets', 'the knowledge, tastes and manners valued by a society’s dominant groups',
      'the number and strength of a person’s social ties', 'the prestige that others grant a person because of their occupation and title'], 'B',
    'Cultural capital is non-financial knowledge, skills, tastes and credentials that signal status and help people succeed, often passed down in families and rewarded by schools. Economic capital is money and property, social capital is the value of social networks, and occupational prestige is a separate measure of status.'),
  mc('10a-3', '10A', 'Medium', 'A child whose parents are in the lowest income group grows up to become a surgeon. This is an example of:',
    ['horizontal mobility', 'intragenerational mobility', 'social reproduction', 'upward intergenerational mobility'], 'D',
    'Intergenerational mobility compares a person’s position with their parents’, and here the move is upward. Intragenerational mobility is change within one person’s lifetime, horizontal mobility is a move between positions of similar rank, and social reproduction is inequality passing unchanged from one generation to the next.'),
  mc('10a-4', '10A', 'Hard', 'Residents of a low-income neighborhood live closer to highways and factories, and they have higher rates of asthma. This pattern is most directly an example of:',
    ['meritocracy', 'the culture of poverty', 'environmental injustice', 'the digital divide'], 'C',
    'Environmental injustice is the concentration of environmental hazards, such as pollution, in poorer and minority communities, a form of spatial inequality that contributes to health disparities. Meritocracy is the idea that position reflects ability and effort, and the digital divide concerns access to technology.'),
  mc('10a-5', '10A', 'Hard', 'The “social gradient in health” refers to the finding that:',
    ['only the very poorest people have worse health than everyone else in a society', 'health improves step by step with each rise in socioeconomic status',
      'wealthier people are sick more often than poorer people', 'health depends only on access to medical care'], 'B',
    'The gradient means health rises at every step of the socioeconomic ladder, not just between the poor and everyone else: the middle class have worse health than the wealthy, as well as better health than the poor. Access to care is only one of many social determinants of health.'),
];
