// 60 original MCAT questions for Chemical and Physical Foundations of Biological Systems, written for this app:
// the AAMC publishes no question bank, and its practice material may not be copied.
//
// Six per content category, two at each tier (Foundation, Intermediate, Exam-level, stored as Easy, Medium and
// Hard). The correct letters were planned before writing, fifteen of each, so no letter is a safe guess. These
// are stand-alone questions; passage sets come next. Every calculated answer is worked out again from the
// wording of the question in tests/mcat-questions.test.js.

const FC4 = 'Physical principles of living systems (Foundational Concept 4)';
const FC5 = 'Chemical principles of living systems (Foundational Concept 5)';

const SKILL = {
  '4A': '4A: Translational motion, forces, work, energy, and equilibrium in living systems',
  '4B': '4B: Importance of fluids for the circulation of blood, gas movement, and gas exchange',
  '4C': '4C: Electrochemistry and electrical circuits and their elements',
  '4D': '4D: How light and sound interact with matter',
  '4E': '4E: Atoms, nuclear decay, electronic structure, and atomic chemical behavior',
  '5A': '5A: Unique nature of water and its solutions',
  '5B': '5B: Nature of molecules and intermolecular interactions',
  '5C': '5C: Separation and purification methods',
  '5D': '5D: Structure, function, and reactivity of biologically relevant molecules',
  '5E': '5E: Principles of chemical thermodynamics and kinetics',
};

const mc = (id, code, difficulty, stem, choices, answer, rationale) => ({
  id: `mcat-cp-${id}`, exam: 'mcat', section: 'CP', domain: code.startsWith('4') ? FC4 : FC5, skill: SKILL[code],
  difficulty, stem, choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })), answer, rationale, source: 'original',
});

export const MCAT_CP_QUESTIONS = [
  // ---- 4A: motion, forces, work, energy and equilibrium ----
  mc('4a-1', '4A', 'Easy', 'A ball is dropped from rest from a height of 20 m. Using g = 10 m/s² and ignoring air resistance, how long does it take to reach the ground?',
    ['1 s', '2 s', '4 s', '20 s'], 'B',
    'From rest, h = ½gt², so t = √(2h/g) = √(2 × 20 / 10) = √4 = 2 s.'),
  mc('4a-2', '4A', 'Easy', 'A net force of 30 N acts on a 6 kg mass. What is the mass’s acceleration?',
    ['0.2 m/s²', '2.5 m/s²', '5 m/s²', '180 m/s²'], 'C',
    'Newton’s second law gives a = F/m = 30 N ÷ 6 kg = 5 m/s².'),
  mc('4a-3', '4A', 'Medium', 'A hoist lifts a 60 kg patient straight up 0.5 m at constant speed. Using g = 10 m/s², how much work does the hoist do on the patient?',
    ['30 J', '60 J', '120 J', '300 J'], 'D',
    'At constant speed the hoist’s force equals the weight, mg = 600 N, so the work is 600 N × 0.5 m = 300 J, all of it going into gravitational potential energy.'),
  mc('4a-4', '4A', 'Medium', 'A car speeds up uniformly from rest to 20 m/s in 8 s. How far does it travel in that time?',
    ['40 m', '80 m', '160 m', '320 m'], 'B',
    'With uniform acceleration the average speed is (0 + 20) ÷ 2 = 10 m/s, and 10 m/s × 8 s = 80 m.'),
  mc('4a-5', '4A', 'Hard', 'A 0.5 kg ball is thrown straight up at 12 m/s. Using g = 10 m/s² and ignoring air resistance, how high does it rise above the point of release?',
    ['0.6 m', '3.6 m', '7.2 m', '14.4 m'], 'C',
    'At the top the speed is zero, so v₀² = 2gh and h = 12² ÷ (2 × 10) = 144 ÷ 20 = 7.2 m. The mass does not matter.'),
  mc('4a-6', '4A', 'Hard', 'A forearm is held horizontal with a 20 N weight in the hand, 35 cm from the elbow. The biceps attaches 5 cm from the elbow and pulls straight up. Ignoring the forearm’s own weight, how hard must the biceps pull to hold the arm still?',
    ['20 N', '70 N', '100 N', '140 N'], 'D',
    'Taking torques about the elbow, F × 5 cm = 20 N × 35 cm, so F = 700 ÷ 5 = 140 N. The short lever arm is why muscles exert forces many times the load.'),

  // ---- 4B: fluids, circulation and gases ----
  mc('4b-1', '4B', 'Easy', 'A force of 50 N presses evenly on an area of 0.02 m². What pressure does it exert?',
    ['1 Pa', '2,500 Pa', '5,000 Pa', '25,000 Pa'], 'B',
    'Pressure is force per area: 50 N ÷ 0.02 m² = 2,500 Pa.'),
  mc('4b-2', '4B', 'Easy', 'Blood flows steadily from a wide, level section of a vessel into a narrower, level section. Compared with the wide section, the narrow section has:',
    ['slower flow and higher pressure', 'slower flow and lower pressure', 'faster flow and higher pressure', 'faster flow and lower pressure'], 'D',
    'By continuity (A₁v₁ = A₂v₂) the blood speeds up where the area shrinks, and by Bernoulli’s equation, at the same height, faster flow means lower pressure.'),
  mc('4b-3', '4B', 'Medium', 'How much greater is the pressure 2.0 m below the surface of a pool of water than at the surface? (Density of water = 1,000 kg/m³, g = 10 m/s².)',
    ['20,000 Pa', '40,000 Pa', '120,000 Pa', '200,000 Pa'], 'A',
    'The extra pressure from the water above is ρgh = 1,000 × 10 × 2.0 = 20,000 Pa. Adding atmospheric pressure would give the total, about 120,000 Pa, but the question asks for the difference.'),
  mc('4b-4', '4B', 'Medium', 'The radius of a blood vessel is halved. By what factor must the pressure difference along it increase to keep the same flow rate, assuming Poiseuille flow?',
    ['2', '4', '8', '16'], 'D',
    'Poiseuille’s law makes flow proportional to r⁴ΔP. Halving r cuts r⁴ to 1/16, so ΔP must rise 16-fold to keep the flow the same.'),
  mc('4b-5', '4B', 'Hard', 'A block with a volume of 0.004 m³ and a density of 800 kg/m³ floats in water (density 1,000 kg/m³). What volume of the block is below the waterline?',
    ['0.0008 m³', '0.0020 m³', '0.0032 m³', '0.0040 m³'], 'C',
    'Floating means the buoyant force equals the weight, so ρ(water) × V(submerged) = ρ(block) × V. The submerged volume is 0.004 × 800 ÷ 1,000 = 0.0032 m³, or 80% of the block.'),
  mc('4b-6', '4B', 'Hard', 'Air is 21% oxygen. At an altitude where the total air pressure is 500 mmHg, what is the partial pressure of oxygen?',
    ['21 mmHg', '105 mmHg', '160 mmHg', '500 mmHg'], 'B',
    'By Dalton’s law a gas’s partial pressure is its mole fraction times the total: 0.21 × 500 = 105 mmHg. About 160 mmHg is the value at sea level, where the total is 760 mmHg.'),

  // ---- 4C: circuits and electrochemistry ----
  mc('4c-1', '4C', 'Easy', 'A 9 V battery is connected across a 3 Ω resistor. What current flows?',
    ['0.33 A', '3 A', '12 A', '27 A'], 'B',
    'Ohm’s law, V = IR, rearranges to I = V/R, so the current is 9 V ÷ 3 Ω = 3 A.'),
  mc('4c-2', '4C', 'Easy', 'A 2 Ω resistor and a 4 Ω resistor are connected in series. What is their equivalent resistance?',
    ['1.33 Ω', '2 Ω', '6 Ω', '8 Ω'], 'C',
    'Resistances in series add: 2 Ω + 4 Ω = 6 Ω. The 1.33 Ω value is what they would give in parallel.'),
  mc('4c-3', '4C', 'Medium', 'A 6 Ω resistor and a 3 Ω resistor are connected in parallel. What is their equivalent resistance?',
    ['2 Ω', '4.5 Ω', '9 Ω', '18 Ω'], 'A',
    'In parallel, 1/R = 1/6 + 1/3 = 1/6 + 2/6 = 3/6, so R = 2 Ω, less than either resistor alone.'),
  mc('4c-4', '4C', 'Medium', 'In a galvanic cell, where does oxidation take place, and what is the sign of ΔG for the cell reaction?',
    ['At the cathode, and ΔG is positive', 'At the anode, and ΔG is positive', 'At the cathode, and ΔG is negative', 'At the anode, and ΔG is negative'], 'D',
    'Oxidation always happens at the anode. A galvanic cell runs on its own, so its reaction is spontaneous: E°cell is positive and ΔG = −nFE is negative.'),
  mc('4c-5', '4C', 'Hard', 'A 10 μF capacitor is charged to 100 V. How much energy does it store?',
    ['0.05 J', '0.1 J', '0.5 J', '1 J'], 'A',
    'The energy stored is ½CV² = ½ × (10 × 10⁻⁶ F) × (100 V)² = ½ × 10⁻⁵ × 10⁴ = 0.05 J.'),
  mc('4c-6', '4C', 'Hard', 'A cell reaction transfers 2 moles of electrons per mole of reaction and has E°cell = +1.10 V. Using F = 96,500 C/mol, what is ΔG° for the reaction?',
    ['−212 kJ/mol', '−106 kJ/mol', '+106 kJ/mol', '+212 kJ/mol'], 'A',
    'ΔG° = −nFE° = −2 × 96,500 × 1.10 = −212,300 J/mol, about −212 kJ/mol. The negative sign matches a positive cell potential.'),

  // ---- 4D: light and sound ----
  mc('4d-1', '4D', 'Easy', 'A sound wave with a frequency of 170 Hz travels through air at 340 m/s. What is its wavelength?',
    ['0.5 m', '2 m', '170 m', '57,800 m'], 'B',
    'Every wave obeys v = fλ, so the wavelength is λ = v/f = 340 m/s ÷ 170 Hz = 2 m.'),
  mc('4d-2', '4D', 'Easy', 'Which of these carries the most energy per photon?',
    ['Infrared radiation', 'Microwaves', 'Ultraviolet radiation', 'Visible red light'], 'C',
    'Photon energy is E = hf, so the highest frequency carries the most energy. Of these, ultraviolet has the highest frequency.'),
  mc('4d-3', '4D', 'Medium', 'The sound level near a machine rises from 40 dB to 60 dB. By what factor has the sound intensity increased?',
    ['1.5', '20', '100', '1,000'], 'C',
    'Each 10 dB is a tenfold increase in intensity, so 20 dB more is 10 × 10 = 100 times the intensity.'),
  mc('4d-4', '4D', 'Medium', 'Light passes from air into water, whose index of refraction is 1.33. Taking the speed of light in a vacuum as 3.00 × 10⁸ m/s, how fast does the light travel in water?',
    ['1.33 × 10⁸ m/s', '2.26 × 10⁸ m/s', '3.00 × 10⁸ m/s', '3.99 × 10⁸ m/s'], 'B',
    'The index of refraction is n = c/v, so v = c/n = (3.00 × 10⁸) ÷ 1.33 ≈ 2.26 × 10⁸ m/s. Light is always slower in a material than in a vacuum.'),
  mc('4d-5', '4D', 'Hard', 'An object is placed 60 cm in front of a converging lens with a focal length of 20 cm. How far from the lens does the image form?',
    ['12 cm', '15 cm', '20 cm', '30 cm'], 'D',
    'The thin lens equation gives 1/dᵢ = 1/f − 1/dₒ = 1/20 − 1/60 = 2/60, so dᵢ = 30 cm: a real image on the far side of the lens.'),
  mc('4d-6', '4D', 'Hard', 'A patient’s corrective lens has a power of −2.5 diopters. Which describes the lens?',
    ['A converging lens with a focal length of 0.4 m, for farsightedness', 'A converging lens with a focal length of 2.5 m, for nearsightedness', 'A diverging lens with a focal length of 0.4 m, for nearsightedness', 'A diverging lens with a focal length of 2.5 m, for farsightedness'], 'C',
    'Power is 1/f with f in meters, so f = 1 ÷ (−2.5) = −0.4 m. A negative focal length means a diverging lens, which is how nearsightedness is corrected.'),

  // ---- 4E: atoms, nuclear decay and electronic structure ----
  mc('4e-1', '4E', 'Easy', 'Uranium-238 (Z = 92) undergoes alpha decay. What nucleus is produced?',
    ['Ra-230 (Z = 88)', 'U-234 (Z = 92)', 'Pa-234 (Z = 91)', 'Th-234 (Z = 90)'], 'D',
    'An alpha particle carries away 2 protons and 2 neutrons, so A drops by 4 to 234 and Z drops by 2 to 90, which is thorium.'),
  mc('4e-2', '4E', 'Easy', 'What fraction of a radioactive sample remains after 5 half-lives?',
    ['1/10', '1/16', '1/32', '1/64'], 'C',
    'Each half-life halves what is left: (½)⁵ = 1/32.'),
  mc('4e-3', '4E', 'Medium', 'Carbon-14 (Z = 6) undergoes beta-minus decay. What nucleus is produced?',
    ['N-14 (Z = 7)', 'B-14 (Z = 5)', 'C-13 (Z = 6)', 'Be-10 (Z = 4)'], 'A',
    'In beta-minus decay a neutron becomes a proton and an electron is emitted, so Z rises by 1 to 7 (nitrogen) and A stays 14.'),
  mc('4e-4', '4E', 'Medium', 'Which of these atoms has the highest first ionization energy?',
    ['Sodium', 'Magnesium', 'Chlorine', 'Argon'], 'D',
    'All four are in period 3, and ionization energy rises across a period. Argon, a noble gas with a full outer shell, is highest.'),
  mc('4e-5', '4E', 'Hard', 'An electron dropping between energy levels emits a photon with a wavelength of 500 nm. Using h = 6.63 × 10⁻³⁴ J·s and c = 3.00 × 10⁸ m/s, what is the photon’s energy?',
    ['3.98 × 10⁻²⁸ J', '1.33 × 10⁻²⁷ J', '1.99 × 10⁻²⁵ J', '3.98 × 10⁻¹⁹ J'], 'D',
    'E = hc/λ = (6.63 × 10⁻³⁴ × 3.00 × 10⁸) ÷ (500 × 10⁻⁹) ≈ 3.98 × 10⁻¹⁹ J. Leaving the wavelength in nanometres gives 3.98 × 10⁻²⁸ J instead.'),
  mc('4e-6', '4E', 'Hard', 'Thorium-232 (Z = 90) undergoes one alpha decay followed by two beta-minus decays. What nucleus results?',
    ['Ra-228 (Z = 88)', 'Th-228 (Z = 90)', 'Ac-228 (Z = 89)', 'U-232 (Z = 92)'], 'B',
    'The alpha decay gives A = 228 and Z = 88. Each beta-minus decay raises Z by 1 without changing A, so two of them give Z = 90: thorium-228.'),

  // ---- 5A: water, acids, bases and solutions ----
  mc('5a-1', '5A', 'Easy', 'What is the pH of a 0.001 M solution of HCl, a strong acid?',
    ['1', '3', '11', '13'], 'B',
    'A strong acid ionizes completely, so [H⁺] = 0.001 = 10⁻³ M and pH = −log(10⁻³) = 3.'),
  mc('5a-2', '5A', 'Easy', 'At 25 °C a solution has [H⁺] = 1 × 10⁻⁵ M. What is its pOH?',
    ['5', '7', '9', '14'], 'C',
    'The pH is 5, and at 25 °C pH + pOH = 14, so pOH = 9.'),
  mc('5a-3', '5A', 'Medium', 'A buffer made from a weak acid with pKa 6.8 has a pH of 7.8. What is the ratio of conjugate base to acid, [A⁻]/[HA]?',
    ['10', '100', '1,000', '10,000'], 'A',
    'Henderson–Hasselbalch: 7.8 = 6.8 + log([A⁻]/[HA]), so log of the ratio is 1 and the ratio is 10.'),
  mc('5a-4', '5A', 'Medium', 'Which 0.1 m aqueous solution has the lowest freezing point?',
    ['CaCl₂', 'Glucose', 'NaCl', 'Urea'], 'A',
    'Freezing point depression is proportional to the number of dissolved particles. CaCl₂ gives three ions per formula unit, NaCl two, and glucose and urea one each.'),
  mc('5a-5', '5A', 'Hard', 'What is the osmotic pressure of a 0.15 M NaCl solution at 310 K? Assume complete dissociation and use R = 0.0821 L·atm/(mol·K).',
    ['1.9 atm', '3.8 atm', '7.6 atm', '15.3 atm'], 'C',
    'π = iMRT = 2 × 0.15 × 0.0821 × 310 ≈ 7.6 atm. Leaving out the van ’t Hoff factor of 2 gives about 3.8 atm.'),
  mc('5a-6', '5A', 'Hard', 'Silver chloride has Ksp = 1.8 × 10⁻¹⁰. What is its molar solubility in pure water?',
    ['9.0 × 10⁻¹¹ M', '1.8 × 10⁻¹⁰ M', '3.6 × 10⁻¹⁰ M', '1.34 × 10⁻⁵ M'], 'D',
    'AgCl dissolves into equal amounts of Ag⁺ and Cl⁻, so Ksp = s², and s = √(1.8 × 10⁻¹⁰) ≈ 1.34 × 10⁻⁵ M.'),

  // ---- 5B: molecules and intermolecular interactions ----
  mc('5b-1', '5B', 'Easy', 'What is the shape of a methane (CH₄) molecule, and its H–C–H bond angle?',
    ['Tetrahedral, 109.5°', 'Trigonal planar, 120°', 'Linear, 180°', 'Bent, 104.5°'], 'A',
    'Carbon has four bonding groups and no lone pairs, which VSEPR arranges as a tetrahedron with 109.5° angles.'),
  mc('5b-2', '5B', 'Easy', 'Which of these compounds can form hydrogen bonds with other molecules of the same compound?',
    ['CH₄', 'CH₃OCH₃', 'CH₃CH₂OH', 'CH₃Cl'], 'C',
    'Hydrogen bonding needs H bonded directly to N, O or F. Only ethanol has an O–H. Dimethyl ether has oxygen but no H on it.'),
  mc('5b-3', '5B', 'Medium', 'A molecule has two chiral centers. What is the largest number of stereoisomers it can have?',
    ['4', '6', '8', '16'], 'A',
    'The maximum is 2ⁿ for n chiral centers, and 2² = 4. If the molecule has an internal plane of symmetry, a meso form reduces this to 3.'),
  mc('5b-4', '5B', 'Medium', 'What is the hybridization of the carbon atom in formaldehyde, H₂C=O?',
    ['sp', 'sp²', 'sp³', 'sp³d'], 'B',
    'The carbon has three electron groups (two C–H bonds and the double bond), which makes it sp² and trigonal planar.'),
  mc('5b-5', '5B', 'Hard', 'In which property do a pair of enantiomers differ?',
    ['Boiling point', 'Solubility in water', 'The direction in which they rotate plane-polarized light', 'Molecular mass'], 'C',
    'Enantiomers have identical physical properties in a non-chiral setting, except that they rotate plane-polarized light by equal amounts in opposite directions.'),
  mc('5b-6', '5B', 'Hard', 'Propane, dimethyl ether and ethanol have similar molar masses. Which lists them from lowest to highest boiling point?',
    ['Ethanol < dimethyl ether < propane', 'Dimethyl ether < propane < ethanol', 'Propane < ethanol < dimethyl ether', 'Propane < dimethyl ether < ethanol'], 'D',
    'Propane has only dispersion forces; dimethyl ether is polar, adding dipole–dipole forces; ethanol can hydrogen bond, which is strongest. So the boiling points rise in that order.'),

  // ---- 5C: separation and purification ----
  mc('5c-1', '5C', 'Easy', 'On a TLC plate the solvent front moves 10 cm and a compound moves 4 cm. What is the compound’s Rf value?',
    ['0.4', '0.6', '2.5', '4.0'], 'A',
    'Rf is the compound’s distance divided by the solvent front’s: 4 ÷ 10 = 0.4. It can never be more than 1.'),
  mc('5c-2', '5C', 'Easy', 'Which method best separates two liquids that mix completely and boil at 60 °C and 110 °C?',
    ['Simple distillation', 'Fractional distillation', 'Size-exclusion chromatography', 'Recrystallization'], 'A',
    'The boiling points are 50 °C apart, well over the roughly 25 °C difference that simple distillation needs. Fractional distillation is for closer boiling points.'),
  mc('5c-3', '5C', 'Medium', 'On a silica TLC plate run with a nonpolar solvent, which compound travels farthest?',
    ['Benzoic acid', 'Benzyl alcohol', 'Toluene', 'Benzamide'], 'C',
    'Silica is polar, so polar compounds cling to it. Toluene is the least polar of the four, so it moves farthest and has the highest Rf.'),
  mc('5c-4', '5C', 'Medium', 'A solution of benzoic acid and naphthalene in ether is shaken with aqueous NaOH. Where does the benzoic acid end up?',
    ['In the ether layer, unchanged', 'In the aqueous layer, as sodium benzoate', 'In the ether layer, as sodium benzoate', 'In the aqueous layer, unchanged'], 'B',
    'NaOH deprotonates the carboxylic acid into the benzoate ion, whose charge makes it dissolve in water. Naphthalene has no acidic proton and stays in the ether.'),
  mc('5c-5', '5C', 'Hard', 'Proteins of 150 kDa, 60 kDa and 15 kDa are run through a size-exclusion column. In what order do they come out?',
    ['15, 60, then 150 kDa', '60, 15, then 150 kDa', '150, 15, then 60 kDa', '150, 60, then 15 kDa'], 'D',
    'Large proteins cannot enter the pores of the beads and take the shortest path, so they elute first. Smaller proteins wander through the pores and come out later.'),
  mc('5c-6', '5C', 'Hard', 'A 100 kDa protein is made of four identical subunits held together only by noncovalent forces. Where does it appear on an SDS-PAGE gel?',
    ['25 kDa', '50 kDa', '75 kDa', '100 kDa'], 'A',
    'SDS denatures the protein and breaks up noncovalent associations, so the four identical subunits run separately as one band at 100 ÷ 4 = 25 kDa.'),

  // ---- 5D: biologically relevant molecules ----
  mc('5d-1', '5D', 'Easy', 'How many water molecules are released when three amino acids join into a tripeptide?',
    ['1', '2', '3', '4'], 'B',
    'Three amino acids in a chain are joined by two peptide bonds, and each bond forms by condensation, releasing one water.'),
  mc('5d-2', '5D', 'Easy', 'Which amino acid is not chiral?',
    ['Alanine', 'Serine', 'Leucine', 'Glycine'], 'D',
    'Glycine’s side chain is a hydrogen atom, so its alpha carbon carries two identical groups and is not a chiral center.'),
  mc('5d-3', '5D', 'Medium', 'Which compound reacts most readily with a nucleophile by nucleophilic acyl substitution?',
    ['Acetamide', 'Methyl acetate', 'Acetyl chloride', 'Acetic anhydride'], 'C',
    'Reactivity follows how good the leaving group is: acid chlorides are most reactive, then anhydrides, esters and amides. Chloride is the best leaving group.'),
  mc('5d-4', '5D', 'Medium', 'What is formed when 2-propanol, a secondary alcohol, is oxidized?',
    ['Acetone (propanone)', 'Propanal', 'Propanoic acid', 'Propene'], 'A',
    'Oxidizing a secondary alcohol gives a ketone; for 2-propanol, that is acetone. Aldehydes and carboxylic acids come from primary alcohols.'),
  mc('5d-5', '5D', 'Hard', '(R)-2-bromobutane reacts with hydroxide ion by an SN2 mechanism. What is the product?',
    ['(R)-2-butanol only', '(S)-2-butanol only', 'A racemic mixture of 2-butanol', '2-butene only'], 'B',
    'SN2 goes by backside attack, which inverts the stereocentre. The hydroxyl takes the bromine’s place at the highest priority, so R becomes S.'),
  mc('5d-6', '5D', 'Hard', 'At which carbon do α-D-glucopyranose and β-D-glucopyranose differ?',
    ['C-2', 'C-5, which sets whether the sugar is D or L', 'C-6', 'C-1, the anomeric carbon'], 'D',
    'Closing the ring makes C-1 a new chiral center, the anomeric carbon. The α and β anomers differ only in the orientation of its hydroxyl group.'),

  // ---- 5E: thermodynamics and kinetics ----
  mc('5e-1', '5E', 'Easy', 'A reaction has a negative ΔH and a positive ΔS. When is it spontaneous?',
    ['At all temperatures', 'Only at low temperatures', 'Only at high temperatures', 'Never'], 'A',
    'ΔG = ΔH − TΔS. A negative ΔH and a negative −TΔS term make ΔG negative at every temperature.'),
  mc('5e-2', '5E', 'Easy', 'What does a catalyst do to a reaction?',
    ['It makes ΔG more negative', 'It raises the equilibrium constant', 'It lowers the activation energy', 'It makes the reaction more exothermic'], 'C',
    'A catalyst provides a pathway with a lower activation energy, speeding up both directions. It changes neither ΔG, ΔH nor K.'),
  mc('5e-3', '5E', 'Medium', 'How much heat does it take to warm 200 g of water from 25 °C to 35 °C? The specific heat of water is 4.18 J/(g·°C).',
    ['4,180 J', '8,360 J', '29,260 J', '83,600 J'], 'B',
    'q = mcΔT = 200 × 4.18 × 10 = 8,360 J. Using 35 °C instead of the 10 °C change gives 29,260 J.'),
  mc('5e-4', '5E', 'Medium', 'Doubling [A] makes a reaction four times faster, while doubling [B] leaves the rate unchanged. What is the rate law?',
    ['rate = k[A]²[B]', 'rate = k[A][B]', 'rate = k[B]²', 'rate = k[A]²'], 'D',
    'Doubling [A] quadruples the rate, so the reaction is second order in A. The rate does not depend on B, so B does not appear.'),
  mc('5e-5', '5E', 'Hard', 'A reaction has K = 20 and, at one moment, a reaction quotient Q = 5. Which way does it shift, and why?',
    ['Towards products, because Q < K', 'Towards reactants, because Q < K', 'Towards products, because Q > K', 'Neither way, because it is at equilibrium'], 'A',
    'When Q is less than K there are too few products compared with equilibrium, so the reaction runs forward until Q reaches K.'),
  mc('5e-6', '5E', 'Hard', 'A reaction has ΔH = +30 kJ/mol and ΔS = +120 J/(mol·K). At what temperatures is it spontaneous?',
    ['Above 25 K', 'Above 250 K', 'Below 250 K', 'Above 4,000 K'], 'B',
    'Both are positive, so ΔG = ΔH − TΔS is negative once TΔS exceeds ΔH: T > 30,000 ÷ 120 = 250 K.'),
];
