// 54 original MCAT questions for Biological and Biochemical Foundations of Living Systems, written for this app:
// the AAMC publishes no question bank, and its practice material may not be copied.
//
// Six per content category, two at each tier (Foundation, Intermediate, Exam-level, stored as Easy, Medium and
// Hard). The correct letters were planned before writing, 14, 13, 14 and 13 on A to D, so no letter is a safe
// guess. These are stand-alone questions; the passage sets are in js/questions/mcat-bb-passages.js. Every
// calculated answer is worked out again from the wording of the question in tests/mcat-questions.test.js.

const FC1 = 'Biomolecules (Foundational Concept 1)';
const FC2 = 'Cells (Foundational Concept 2)';
const FC3 = 'Organ systems (Foundational Concept 3)';

const SKILL = {
  '1A': '1A: Structure and function of proteins and their constituent amino acids',
  '1B': '1B: Transmission of genetic information from the gene to the protein',
  '1C': '1C: Transmission of heritable information from generation to generation and the processes that increase genetic diversity',
  '1D': '1D: Principles of bioenergetics and fuel molecule metabolism',
  '2A': '2A: Assemblies of molecules, cells, and groups of cells within single cellular and multicellular organisms',
  '2B': '2B: The structure, growth, physiology, and genetics of prokaryotes and viruses',
  '2C': '2C: Processes of cell division, differentiation, and specialization',
  '3A': '3A: Structure and functions of the nervous and endocrine systems and ways in which these systems coordinate the organ systems',
  '3B': '3B: Structure and integrative functions of the main organ systems',
};
const DOMAIN = { 1: FC1, 2: FC2, 3: FC3 };

const mc = (id, code, difficulty, stem, choices, answer, rationale) => ({
  id: `mcat-bb-${id}`, exam: 'mcat', section: 'BB', domain: DOMAIN[code[0]], skill: SKILL[code],
  difficulty, stem, choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })), answer, rationale, source: 'original',
});

export const MCAT_BB_QUESTIONS = [
  // ---- 1A: amino acids and proteins ----
  mc('1a-1', '1A', 'Easy', 'How many peptide bonds are there in a linear peptide of 12 amino acids?',
    ['10', '11', '12', '13'], 'B',
    'Each peptide bond joins two neighboring amino acids, so a chain of n amino acids has n − 1 of them: 12 − 1 = 11. Forming each bond also releases one molecule of water.'),
  mc('1a-2', '1A', 'Easy', 'Which amino acid’s side chain can form a disulfide bond?',
    ['Serine', 'Methionine', 'Tyrosine', 'Cysteine'], 'D',
    'Two cysteine side chains, each ending in a thiol (–SH), can be oxidized to a covalent S–S bridge that stabilizes a protein’s tertiary or quaternary structure. Methionine also contains sulfur, but as a thioether with no free –SH, so it cannot form disulfides.'),
  mc('1a-3', '1A', 'Medium', 'Aspartic acid has pKa values of 2.1 (α-carboxyl), 3.9 (side chain) and 9.8 (α-amino). What is its isoelectric point?',
    ['3.0', '5.3', '6.0', '6.9'], 'A',
    'The neutral form of aspartic acid exists between the first two deprotonations, with the α-carboxyl deprotonated (−1), the amino group protonated (+1) and the side chain still protonated (0). The pI is the average of the pKa values on either side of that form: (2.1 + 3.9) ÷ 2 = 3.0. Averaging the two α-groups gives 6.0, and averaging all three pKa values gives 5.3.'),
  mc('1a-4', '1A', 'Medium', 'The α-helices and β-sheets of a protein are held together mainly by:',
    ['hydrogen bonds between backbone C=O and N–H groups', 'disulfide bonds between cysteine side chains',
      'hydrophobic interactions among nonpolar side chains', 'ionic bonds between oppositely charged side chains'], 'A',
    'Secondary structure is a property of the backbone: in an α-helix each C=O hydrogen-bonds to the N–H four residues along, and neighboring β-strands pair through backbone hydrogen bonds. Disulfides, hydrophobic interactions and salt bridges between side chains stabilize tertiary and quaternary structure.'),
  mc('1a-5', '1A', 'Hard', 'At pH 7.4, what is the approximate net charge of the tripeptide Lys–Gly–Asp? Use pKa values of about 2 for the C-terminal carboxyl, 3.9 for the aspartate side chain, 9 for the N-terminal amino group and 10.5 for the lysine side chain.',
    ['−2', '−1', '0', '+2'], 'C',
    'Each group is charged when the pH is on its charged side of its pKa. The N-terminal amino group (9) and the lysine side chain (10.5) are protonated, +1 each; the aspartate side chain (3.9) and the C-terminal carboxyl (2) are deprotonated, −1 each. Glycine’s own amino and carboxyl groups are tied up in peptide bonds. The total is 0. Counting only the negative groups gives −2, and only the positive ones +2.'),
  mc('1a-6', '1A', 'Hard', 'An enzyme uses an active-site histidine, with a side-chain pKa of 6.0, as a base, so the histidine must be deprotonated for the enzyme to work. About what fraction of the enzyme is active at pH 5.0?',
    ['9%', '50%', '91%', '99%'], 'A',
    'By the Henderson–Hasselbalch equation, [deprotonated] / [protonated] = 10^(pH − pKa) = 10^(5.0 − 6.0) = 1/10. So 1 part in 11, about 9%, is deprotonated and active. 91% is the protonated share, and 50% would apply only when the pH equals the pKa.'),

  // ---- 1B: from gene to protein ----
  mc('1b-1', '1B', 'Easy', 'A sample of double-stranded DNA is 30% adenine. What percentage of its bases is guanine?',
    ['10%', '15%', '20%', '30%'], 'C',
    'Base pairing makes A = T and G = C (Chargaff’s rules). With 30% A there is 30% T, leaving 40% for G and C together, so 20% is guanine.'),
  mc('1b-2', '1B', 'Easy', 'During transcription, which DNA strand does RNA polymerase read, and in which direction does it build the RNA?',
    ['The template strand; it builds RNA 5′ to 3′', 'The template strand; it builds RNA 3′ to 5′',
      'The coding strand, whose sequence the RNA matches; it builds RNA 5′ to 3′', 'The coding strand; it builds RNA 3′ to 5′'], 'A',
    'RNA polymerase reads the template strand 3′ to 5′ and adds each nucleotide to the 3′ end of the growing RNA, so the RNA grows 5′ to 3′. The RNA ends up with the same sequence as the coding strand, with U in place of T.'),
  mc('1b-3', '1B', 'Medium', 'The coding region of a mature mRNA, from the start codon through the stop codon, is 1,203 nucleotides long. How many amino acids are in the protein it encodes?',
    ['399', '400', '401', '1,203'], 'B',
    '1,203 ÷ 3 = 401 codons. The last is the stop codon, which is read by a release factor rather than a tRNA and adds no amino acid, so the protein has 400. The first methionine is counted, since the start codon is part of the region.'),
  mc('1b-4', '1B', 'Medium', 'A point mutation changes the codon UAC, for tyrosine, to UAA. What kind of mutation is this?',
    ['Silent', 'Missense', 'Nonsense', 'Frameshift'], 'C',
    'UAA is a stop codon, so the protein ends early at this point: a nonsense mutation. A silent mutation would keep the same amino acid, a missense mutation would swap it for another, and a frameshift needs an insertion or deletion that is not a multiple of three nucleotides.'),
  mc('1b-5', '1B', 'Hard', 'The template strand of a stretch of DNA reads 3′-TACGGATTC-5′. Which amino acids does it encode? (Codons: AUG = Met, CCU = Pro, AAG = Lys, UAC = Tyr, GGA = Gly, UUC = Phe)',
    ['Tyr–Gly–Phe', 'Met–Pro–Lys', 'Lys–Pro–Met', 'Met–Gly–Phe'], 'B',
    'The mRNA is complementary and antiparallel to the template: 3′-TAC GGA TTC-5′ is transcribed as 5′-AUG CCU AAG-3′, which reads Met–Pro–Lys. Reading the template itself as if it were the mRNA gives Tyr–Gly–Phe, and reading the codons in reverse order gives Lys–Pro–Met.'),
  mc('1b-6', '1B', 'Hard', 'In a eukaryotic gene, a mutation destroys the 5′ splice site at the start of intron 2. What is the most likely direct result?',
    ['Transcription of the gene stops at intron 2', 'The mRNA lacks its poly(A) tail',
      'Exon 2 is translated inside the nucleus', 'Intron 2 is kept in the mature mRNA'], 'D',
    'The spliceosome recognizes an intron by its splice sites, so without the 5′ site intron 2 is not removed (or a nearby lookalike site is used instead). A retained intron usually brings in premature stop codons or shifts the reading frame. Transcription and polyadenylation are unaffected, and translation happens in the cytoplasm.'),

  // ---- 1C: heredity and genetic diversity ----
  mc('1c-1', '1C', 'Easy', 'Two parents are both heterozygous for an autosomal recessive disorder. What is the probability that their first child is affected?',
    ['1/16', '1/4', '1/2', '3/4'], 'B',
    'Each parent passes on the recessive allele with probability 1/2, so a child is homozygous recessive with probability 1/2 × 1/2 = 1/4. 3/4 is the chance the child shows the dominant phenotype, and 1/2 is the chance of being a carrier.'),
  mc('1c-2', '1C', 'Easy', 'In which phase of meiosis do homologous chromosomes separate?',
    ['Anaphase I', 'Anaphase II', 'Metaphase I', 'Prophase II'], 'A',
    'In anaphase I the paired homologs are pulled to opposite poles, halving the chromosome number. Sister chromatids stay together until anaphase II, which resembles a mitotic anaphase.'),
  mc('1c-3', '1C', 'Medium', 'An autosomal recessive condition affects 1 in 10,000 people in a population in Hardy–Weinberg equilibrium. About what fraction of the population are carriers?',
    ['1 in 5,000', '1 in 200', '1 in 100', '1 in 50'], 'D',
    'q² = 1/10,000, so q = 0.01 and p = 0.99. Carriers make up 2pq = 2 × 0.99 × 0.01 ≈ 0.02, about 1 in 50. Using q alone gives 1 in 100, and 2q² gives 1 in 5,000.'),
  mc('1c-4', '1C', 'Medium', 'A man with an X-linked recessive disorder has children with a woman who is not a carrier. What is the probability that a son of theirs is affected?',
    ['0', '1/4', '1/2', '1'], 'A',
    'A son gets his X chromosome from his mother, who has no disease allele, and his Y from his father, so no son is affected. Every daughter, though, receives the father’s X and is a carrier.'),
  mc('1c-5', '1C', 'Hard', 'In a testcross of a plant heterozygous for two linked genes, 1,000 offspring included 85 and 65 in the two recombinant classes. How far apart are the genes?',
    ['6.5 cM', '8.5 cM', '15 cM', '30 cM'], 'C',
    'The recombination frequency is (85 + 65) ÷ 1,000 = 0.15, and 1% recombination is defined as 1 centimorgan, so the genes are 15 cM apart. Each recombinant class alone gives 8.5 or 6.5, and 30 counts each recombinant twice.'),
  mc('1c-6', '1C', 'Hard', 'In pea plants, round seeds (R) are dominant to wrinkled (r) and yellow (Y) to green (y), and the two genes assort independently. What fraction of the offspring of RrYy × Rryy have round, green seeds?',
    ['1/8', '3/16', '3/8', '9/16'], 'C',
    'Take the genes one at a time and multiply. Rr × Rr gives round seeds 3/4 of the time, and Yy × yy gives green (yy) seeds 1/2 of the time, so 3/4 × 1/2 = 3/8. 3/16 and 9/16 come from crossing two double heterozygotes, which this cross is not.'),

  // ---- 1D: bioenergetics and metabolism ----
  mc('1d-1', '1D', 'Easy', 'Where in a eukaryotic cell does glycolysis take place?',
    ['In the cytosol', 'In the mitochondrial matrix', 'On the inner mitochondrial membrane', 'In the nucleus'], 'A',
    'Glycolysis, which splits glucose into two pyruvate, runs in the cytosol and needs no oxygen. The citric acid cycle runs in the mitochondrial matrix, and the electron transport chain sits in the inner mitochondrial membrane.'),
  mc('1d-2', '1D', 'Easy', 'What is the final electron acceptor of the electron transport chain in aerobic respiration?',
    ['NAD⁺', 'FAD', 'Pyruvate', 'O₂'], 'D',
    'At complex IV, electrons pass to O₂, which is reduced to water. NAD⁺ and FAD are the carriers that bring electrons to the chain, as NADH and FADH₂, and pyruvate is the product of glycolysis.'),
  mc('1d-3', '1D', 'Medium', 'An enzyme has a Km of 2 mM and a Vmax of 100 μmol/min. What is the reaction rate when the substrate concentration is 6 mM?',
    ['25 μmol/min', '50 μmol/min', '75 μmol/min', '100 μmol/min'], 'C',
    'By the Michaelis–Menten equation, v = Vmax[S] / (Km + [S]) = 100 × 6 / (2 + 6) = 75 μmol/min. The rate is 50 μmol/min only when [S] equals Km, and it approaches 100 μmol/min only at very high [S].'),
  mc('1d-4', '1D', 'Medium', 'How does a competitive inhibitor change an enzyme’s apparent Km and Vmax?',
    ['Km falls; Vmax is unchanged', 'Km rises; Vmax is unchanged', 'Km stays the same; Vmax falls', 'Km and Vmax both fall'], 'B',
    'A competitive inhibitor competes with the substrate for the active site, so more substrate is needed to reach half the maximum rate (Km rises), but enough substrate outcompetes it completely, so Vmax is unchanged. A pure noncompetitive inhibitor lowers Vmax without changing Km, and an uncompetitive inhibitor lowers both.'),
  mc('1d-5', '1D', 'Hard', 'About how many NADH are produced from one molecule of glucose by glycolysis, the pyruvate dehydrogenase reaction and the citric acid cycle together?',
    ['2', '6', '8', '10'], 'D',
    'Glycolysis makes 2 NADH, pyruvate dehydrogenase makes 1 per pyruvate (2 in all), and the citric acid cycle makes 3 per turn, with two turns per glucose (6 in all): 2 + 2 + 6 = 10. The cycle also makes 2 FADH₂, which are not NADH.'),
  mc('1d-6', '1D', 'Hard', 'A day’s diet contains 300 g of carbohydrate, 80 g of fat and 70 g of protein. About how many kilocalories does it provide?',
    ['1,800 kcal', '2,200 kcal', '2,550 kcal', '4,050 kcal'], 'B',
    'Carbohydrate and protein each yield about 4 kcal/g and fat about 9 kcal/g: 300 × 4 + 80 × 9 + 70 × 4 = 1,200 + 720 + 280 = 2,200 kcal. Counting everything at 4 kcal/g gives 1,800, counting protein at 9 kcal/g gives 2,550, and counting everything at 9 kcal/g gives 4,050.'),

  // ---- 2A: cells, membranes and tissues ----
  mc('2a-1', '2A', 'Easy', 'Which organelle makes most of the proteins that a cell secretes?',
    ['Rough endoplasmic reticulum', 'Smooth endoplasmic reticulum', 'Golgi apparatus', 'Lysosome'], 'A',
    'Ribosomes on the rough ER make secreted and membrane proteins, threading them into the ER as they are made. The Golgi then modifies and sorts them but does not make them; the smooth ER makes lipids, and lysosomes break molecules down.'),
  mc('2a-2', '2A', 'Easy', 'Which kind of cell junction seals neighboring epithelial cells together so that fluid cannot leak between them?',
    ['Gap junctions', 'Desmosomes', 'Hemidesmosomes', 'Tight junctions'], 'D',
    'Tight junctions join the membranes of neighboring cells into a seal, which is why substances crossing an epithelium such as the gut lining must pass through its cells. Gap junctions are channels between cells, desmosomes anchor cells to one another, and hemidesmosomes anchor them to the basement membrane.'),
  mc('2a-3', '2A', 'Medium', 'If the radius of a spherical cell doubles, by what factor does its surface-area-to-volume ratio change?',
    ['1/4', '1/2', '2', '4'], 'B',
    'Surface area is 4πr² and volume is (4/3)πr³, so the ratio is 3/r, and doubling r halves it. This is one reason cells stay small: volume, and so demand, outgrows the membrane that supplies it.'),
  mc('2a-4', '2A', 'Medium', 'A red blood cell, whose contents are about 300 mOsm/L, is placed in 0.15 M CaCl₂. What happens to the cell?',
    ['It swells and bursts.', 'It keeps its size.', 'It shrinks.', 'It swells, then returns to its size.'], 'C',
    'Each CaCl₂ dissolves into three ions, so 0.15 M CaCl₂ is about 450 mOsm/L, hypertonic to the cell. Water leaves by osmosis and the cell shrinks (crenates). 0.15 M NaCl, at about 300 mOsm/L, would have been isotonic.'),
  mc('2a-5', '2A', 'Hard', 'Which statement best describes the effect of cholesterol on the fluidity of an animal cell’s membrane?',
    ['It lowers fluidity at body temperature but keeps the membrane from stiffening in the cold.',
      'It raises fluidity at every temperature by spacing the phospholipids farther apart from one another.',
      'It lowers fluidity at every temperature by binding the phospholipid tails together.',
      'It has no effect on fluidity; it only anchors membrane proteins in place.'], 'A',
    'Cholesterol’s rigid rings restrain the movement of nearby phospholipid tails, so the membrane is less fluid at body temperature. In the cold, cholesterol gets between the tails and stops them packing tightly, so the membrane does not stiffen. It buffers fluidity rather than pushing it one way.'),
  mc('2a-6', '2A', 'Hard', 'By Fick’s law, the rate at which a gas diffuses across a membrane is proportional to the membrane’s area and to the concentration difference, and inversely proportional to its thickness. If a membrane’s area and its thickness both double, the rate of diffusion:',
    ['halves', 'doubles', 'quadruples', 'stays the same'], 'D',
    'Rate ∝ area × concentration difference ÷ thickness. Doubling the area doubles the rate and doubling the thickness halves it, so the two cancel. Disease that thickens the walls of the alveoli slows gas exchange in the lung for this reason.'),

  // ---- 2B: prokaryotes and viruses ----
  mc('2b-1', '2B', 'Easy', 'Which of the following is found in bacterial cells but not in animal cells?',
    ['Ribosomes', 'A plasma membrane', 'Cytoplasm', 'A peptidoglycan cell wall'], 'D',
    'Most bacteria have a cell wall of peptidoglycan, which is why antibiotics such as penicillin that block its synthesis spare human cells. Animal cells have no cell wall at all. Ribosomes, a plasma membrane and cytoplasm are found in both.'),
  mc('2b-2', '2B', 'Easy', 'A bacterium divides every 20 minutes. Starting from one cell, how many cells are there after 2 hours of unrestricted growth?',
    ['12', '32', '64', '128'], 'C',
    'Two hours is 120 minutes, or 6 generations of 20 minutes, and each generation doubles the number: 2⁶ = 64. Adding two cells per generation would give 12, and 32 and 128 are the results of five and seven doublings.'),
  mc('2b-3', '2B', 'Medium', 'Which process transfers DNA from one bacterium to another through a pilus?',
    ['Conjugation', 'Transformation', 'Transduction', 'Binary fission'], 'A',
    'In conjugation, a donor cell carrying an F plasmid makes a sex pilus that connects it to a recipient, and DNA passes across. In transformation a cell takes up free DNA from its surroundings, and in transduction a bacteriophage carries the DNA. Binary fission is ordinary cell division.'),
  mc('2b-4', '2B', 'Medium', 'Which enzyme must a retrovirus such as HIV bring into the cell in order to establish an infection?',
    ['DNA ligase', 'Reverse transcriptase', 'RNA polymerase II', 'A restriction endonuclease'], 'B',
    'A retrovirus has an RNA genome that must be copied into DNA before it can be built into the host’s chromosomes. Host cells have no enzyme that copies RNA into DNA, so the virus carries its own reverse transcriptase. The host supplies RNA polymerase II, which later transcribes the integrated viral DNA.'),
  mc('2b-5', '2B', 'Hard', 'A bacterial culture in log phase grows from 2 × 10⁵ to 1.6 × 10⁶ cells per mL in 90 minutes. What is its doubling time?',
    ['11 min', '22.5 min', '30 min', '45 min'], 'C',
    'The population grew by a factor of 1.6 × 10⁶ ÷ 2 × 10⁵ = 8, which is 2³, so it doubled three times in 90 minutes: 30 minutes per doubling. Dividing 90 minutes by the factor of 8 gives about 11 minutes, and 22.5 and 45 minutes would mean four and two doublings.'),
  mc('2b-6', '2B', 'Hard', 'Many antibiotics block bacterial 70S ribosomes. Why do they do relatively little harm to human cells?',
    ['Human cells have no ribosomes in their cytoplasm.', 'The nuclear envelope shields human ribosomes from the drugs.',
      'The drugs cannot cross the plasma membrane of human cells.', 'Human cytoplasmic ribosomes are 80S, and the drugs bind them poorly.'], 'D',
    'Eukaryotic cytoplasmic ribosomes (80S, with 60S and 40S subunits) differ enough from bacterial 70S ribosomes (50S and 30S) that these drugs bind them poorly. Human mitochondria, though, have ribosomes resembling bacterial ones, which is one source of these drugs’ side effects.'),

  // ---- 2C: cell division and differentiation ----
  mc('2c-1', '2C', 'Easy', 'A human body cell in G1 has 46 chromosomes. How many chromatids does it have at metaphase of mitosis?',
    ['23', '46', '69', '92'], 'D',
    'The DNA is replicated in S phase, so by metaphase each of the 46 chromosomes is made of two sister chromatids: 92 in all. The chromosome count stays 46 until the sisters separate in anaphase.'),
  mc('2c-2', '2C', 'Easy', 'During which phase of the cell cycle is DNA replicated?',
    ['G1', 'G2', 'S', 'M'], 'C',
    'S (synthesis) phase is when the DNA is copied. G1 and G2 are growth phases, with checkpoints before and after S, and M phase is mitosis itself.'),
  mc('2c-3', '2C', 'Medium', 'How many chromosomes does each human cell have at the end of meiosis I?',
    ['23, each with one chromatid', '23, each with two chromatids', '46, each with one chromatid', '46, each still made of two chromatids'], 'B',
    'Meiosis I separates homologous chromosomes, so each daughter cell gets 23 chromosomes, but the sister chromatids are still joined, so each has two chromatids. Meiosis II then separates the sisters, leaving 23 single-chromatid chromosomes.'),
  mc('2c-4', '2C', 'Medium', 'Which protein, often called the “guardian of the genome,” can halt the cell cycle in G1 when DNA is damaged?',
    ['p53', 'Ras', 'Cyclin D', 'Myc'], 'A',
    'p53 is a tumor suppressor: DNA damage stabilizes it, and it switches on genes such as p21 that stop the cycle in G1, or triggers apoptosis if the damage cannot be repaired. Ras, cyclin D and Myc drive the cycle forward, and their overactive forms are oncogenes.'),
  mc('2c-5', '2C', 'Hard', 'What distinguishes a totipotent cell from a pluripotent one?',
    ['A totipotent cell can divide indefinitely, while a pluripotent cell stops after a set number of divisions.',
      'A totipotent cell can form only one germ layer, while a pluripotent cell can form all three.',
      'A totipotent cell is found only in adults, while a pluripotent cell is found only in embryos.',
      'A totipotent cell can also form tissues outside the embryo, such as the placenta; a pluripotent cell cannot.'], 'D',
    'The zygote and the cells of the earliest cleavage divisions are totipotent: they can give rise to the whole organism and to the placenta and other tissues outside the embryo. Cells of the inner cell mass are pluripotent: they can form all three germ layers, but not those extraembryonic tissues.'),
  mc('2c-6', '2C', 'Hard', 'Nondisjunction of chromosome 21 during meiosis I in one parent produces gametes that are:',
    ['half with two copies of chromosome 21 and half with none', 'half normal, a quarter with two copies and a quarter with none',
      'all with two copies of chromosome 21', 'half normal and half with two copies of chromosome 21'], 'A',
    'If the homologs fail to separate in meiosis I, one daughter cell gets both copies and the other none, and meiosis II passes that on: two gametes with two copies and two with none. Half normal, a quarter with two copies and a quarter with none is the result of nondisjunction in meiosis II.'),

  // ---- 3A: nervous and endocrine systems ----
  mc('3a-1', '3A', 'Easy', 'Which part of a neuron receives most of the signals coming from other neurons?',
    ['The axon terminals', 'The myelin sheath', 'The dendrites', 'The axon hillock'], 'C',
    'Dendrites carry most of the synapses that other neurons make onto a cell. The axon hillock sums those inputs and is where an action potential starts; the axon terminals pass signals on to the next cell; and myelin insulates the axon.'),
  mc('3a-2', '3A', 'Easy', 'Which hormone lowers blood glucose?',
    ['Glucagon', 'Cortisol', 'Epinephrine', 'Insulin'], 'D',
    'Insulin, from the β cells of the pancreatic islets, promotes the uptake of glucose by muscle and fat and its storage as glycogen, lowering blood glucose. Glucagon, cortisol and epinephrine all raise it.'),
  mc('3a-3', '3A', 'Medium', 'What causes the rising (depolarizing) phase of a neuron’s action potential?',
    ['Voltage-gated Na⁺ channels open and Na⁺ flows into the cell.', 'Voltage-gated K⁺ channels open and K⁺ flows out of the neuron.',
      'The Na⁺/K⁺ pump moves Na⁺ into the cell.', 'Ligand-gated channels let Cl⁻ into the cell.'], 'A',
    'Once the membrane reaches threshold, voltage-gated Na⁺ channels open and Na⁺ rushes in down its electrochemical gradient, driving the potential toward positive values. K⁺ flowing out causes repolarization, the pump moves Na⁺ out rather than in, and Cl⁻ entering would hyperpolarize the cell.'),
  mc('3a-4', '3A', 'Medium', 'Steroid hormones such as cortisol typically act by:',
    ['binding G protein–coupled receptors on the cell surface', 'binding receptors inside the cell that change gene transcription',
      'opening ion channels in the plasma membrane', 'triggering the release of stored insulin'], 'B',
    'Steroids are lipid-soluble, so they cross the plasma membrane and bind receptors inside the cell that act as transcription factors. Their effects are slower but longer lasting than those of peptide hormones, which bind receptors on the cell surface such as G protein–coupled receptors.'),
  mc('3a-5', '3A', 'Hard', 'Multiple sclerosis destroys myelin in the central nervous system. What change would be expected in the affected axons?',
    ['Faster conduction, because more of the axon membrane is exposed', 'A resting potential much more negative than usual',
      'Loss of neurotransmitter synthesis in the cell body', 'Slower conduction, because action potentials no longer jump from node to node'], 'D',
    'Myelin lets the action potential jump between the nodes of Ranvier (saltatory conduction). Without it, current leaks away across the membrane, so conduction slows or fails. Nothing about losing myelin makes the resting potential much more negative or stops the cell body from making transmitters.'),
  mc('3a-6', '3A', 'Hard', 'A tumor of the adrenal cortex secretes large amounts of cortisol on its own. What would be expected of the patient’s ACTH and CRH levels?',
    ['Both low, because cortisol suppresses the hypothalamus and the pituitary', 'Both high, because the tumor also stimulates the hypothalamus and the pituitary',
      'ACTH high and CRH low', 'ACTH low and CRH high'], 'A',
    'Cortisol feeds back negatively on both the hypothalamus, which makes CRH, and the anterior pituitary, which makes ACTH. A tumor that makes cortisol on its own drives both down. A high ACTH would instead point to a pituitary tumor making ACTH.'),

  // ---- 3B: the main organ systems ----
  mc('3b-1', '3B', 'Easy', 'A heart beats 70 times per minute and pumps 70 mL with each beat. What is its cardiac output?',
    ['1.0 L/min', '4.9 L/min', '7.0 L/min', '49 L/min'], 'B',
    'Cardiac output = heart rate × stroke volume = 70 beats/min × 70 mL = 4,900 mL/min, or 4.9 L/min, close to the typical resting value of about 5 L/min.'),
  mc('3b-2', '3B', 'Easy', 'Where are most nutrients absorbed in the digestive tract?',
    ['The stomach', 'The large intestine (colon)', 'The small intestine', 'The esophagus'], 'C',
    'The small intestine, lined with villi and microvilli, has an enormous surface area and absorbs most nutrients. The stomach absorbs little besides some water, alcohol and drugs, the large intestine mainly absorbs water and salts, and the esophagus only carries food.'),
  mc('3b-3', '3B', 'Medium', 'A person breathes 12 times a minute with a tidal volume of 500 mL, and the anatomical dead space is 150 mL. What is the alveolar ventilation?',
    ['1.8 L/min', '4.2 L/min', '6.0 L/min', '7.8 L/min'], 'B',
    'Only the air beyond the dead space reaches the alveoli: (500 − 150) mL × 12 per minute = 4,200 mL/min, or 4.2 L/min. 6.0 L/min is the total (minute) ventilation, and 1.8 L/min is the air that only fills the dead space.'),
  mc('3b-4', '3B', 'Medium', 'Which blood vessels have the largest total cross-sectional area, and so the slowest blood flow?',
    ['Arteries', 'Capillaries', 'Arterioles', 'Veins'], 'B',
    'There are billions of capillaries, so together they have by far the largest cross-sectional area. The same volume of blood passes through each level of the circulation every minute, so flow is slowest where the total area is largest, which gives time for exchange with the tissues.'),
  mc('3b-5', '3B', 'Hard', 'A substance is freely filtered by the kidney and is neither reabsorbed nor secreted. Its plasma concentration is 2 mg/mL, its urine concentration is 250 mg/mL, and urine flows at 1 mL/min. What is the glomerular filtration rate?',
    ['0.5 mL/min', '62.5 mL/min', '125 mL/min', '250 mL/min'], 'C',
    'For such a substance (inulin is the classic example), everything filtered ends up in the urine, so the GFR equals its clearance: urine concentration × urine flow ÷ plasma concentration = 250 × 1 ÷ 2 = 125 mL/min, a normal adult value.'),
  mc('3b-6', '3B', 'Hard', 'During strenuous exercise, which change in a working muscle shifts hemoglobin’s oxygen dissociation curve to the right, helping the muscle receive O₂?',
    ['A fall in 2,3-bisphosphoglycerate', 'A rise in the pH of the blood', 'A rise in CO₂, H⁺ and temperature', 'A fall in the temperature of the tissue'], 'C',
    'More CO₂, more H⁺ (a lower pH, the Bohr effect), a higher temperature and more 2,3-BPG all lower hemoglobin’s affinity for O₂, so it unloads more O₂ where these conditions prevail. The other three changes would shift the curve to the left.'),
];
