// 50 original Standard English Conventions questions (Reading and Writing), written for this app rather than
// taken from the College Board bank, so they can ship in the repo and reach every visitor.
//
// Twenty-five on boundaries (punctuation between and within sentences), twenty-five on form, structure and
// sense (agreement, verb form, modifiers and parallel structure).
//
// Targets were fixed before drafting rather than measured and patched afterwards: answer letters rotate to
// 13/13/12/12, difficulty runs 16 easy, 24 medium, 10 hard, and every passage is written past the 25-word
// floor so none of them needs the floor relaxed. The choices here are short grammatical variants of the same
// words, so length carries almost no signal either way, but the correct one is still varied between the
// longer and shorter options rather than being reliably one or the other.
//
// Every question has exactly one defensible answer. Where a distractor would also be acceptable under some
// style guide it has been rewritten, because a question with two right answers teaches the student nothing.

const DOMAIN = 'Standard English Conventions';

const mc = (id, skill, difficulty, passage, stem, choices, answer, rationale) => ({
  id: `og-${id}`, section: 'RW', domain: DOMAIN, skill, difficulty, passage, stem,
  choices: choices.map((text, i) => ({ letter: 'ABCD'[i], text })),
  answer, rationale, source: 'original',
});

const BOU = 'Boundaries';
const FSS = 'Form, Structure, and Sense';

const CONVENTIONS = 'Which choice completes the text so that it conforms to the conventions of Standard English?';

export const STANDARD_ENGLISH_QUESTIONS = [
  // ---- Boundaries ----
  mc('sec-01', BOU, 'Easy',
    'After months of preparation, the expedition finally left the harbor at dawn. The crew had loaded supplies of three ______ food, fresh water, and fuel for the generator.',
    CONVENTIONS, ['kinds:', 'kinds;', 'kinds', 'kinds, and'], 'A',
    'A colon introduces the list that specifies what the three kinds are. A semicolon must join two independent clauses, and the list that follows is not one.'),
  mc('sec-02', BOU, 'Medium',
    'The storm knocked out power across the valley for six days in the middle of winter. Most residents relied on portable ______ a few families left town altogether.',
    CONVENTIONS, ['generators,', 'generators;', 'generators', 'generators:'], 'B',
    'Both halves are complete sentences, so a semicolon is needed. A comma alone would splice them together, and a colon would promise an explanation of the generators that never comes.'),
  mc('sec-03', BOU, 'Medium',
    'The observatory sits on a ridge above the treeline, where the air is thin and unusually dry. On clear ______ the telescope can resolve detail invisible from the valley floor.',
    CONVENTIONS, ['nights, which', 'nights and', 'nights,', 'nights;'], 'C',
    'An introductory phrase is set off from the main clause by a comma. The other options would either create a fragment or join the phrase to the clause without the pause the sentence needs.'),
  mc('sec-04', BOU, 'Easy',
    'The library had planned to close the reading room for a month of repairs. The work took far longer than expected, and the room stayed shut until the following ______',
    CONVENTIONS, ['spring,', 'spring;', 'spring:', 'spring.'], 'D',
    'The sentence is complete and nothing follows it, so it ends with a full stop. Each of the other marks would leave the reader waiting for something more.'),
  mc('sec-05', BOU, 'Medium',
    'Amara had spent two years photographing the salt flats in every season and every light. Her ______ published last autumn, collects more than a hundred of those images.',
    CONVENTIONS, ['book,', 'book', 'book;', 'book:'], 'A',
    'The phrase "published last autumn" is nonessential and sits between two commas, so the first of the pair is needed here. The other marks would cut the subject off from its verb.'),
  mc('sec-06', BOU, 'Hard',
    'The committee reviewed applications from four countries over the course of a single week. The strongest ______ though it arrived a day past the deadline, came from a school in Lisbon.',
    CONVENTIONS, ['proposal;', 'proposal,', 'proposal', 'proposal:'], 'B',
    'A nonessential clause is enclosed in a pair of commas, and this is the opening one. A semicolon or colon would break the sentence apart before its verb appears.'),
  mc('sec-07', BOU, 'Easy',
    'Every autumn the same flock returns to the estuary and settles on the mudflats to feed. The birds travel from breeding grounds in ______ some of them covering four thousand miles.',
    CONVENTIONS, ['Iceland;', 'Iceland.', 'Iceland,', 'Iceland:'], 'C',
    'What follows is a participial phrase describing the birds, not a complete sentence, so a comma attaches it. A semicolon or full stop would leave that phrase stranded as a fragment.'),
  mc('sec-08', BOU, 'Medium',
    'The recipe has been passed down through four generations of the same family in Naples. It calls for only three ______ flour, water, and a little salt from the bay.',
    CONVENTIONS, ['ingredients,', 'ingredients;', 'ingredients', 'ingredients:'], 'D',
    'A colon introduces a list that specifies the three ingredients just announced. A comma would run the list into the clause, and a semicolon requires an independent clause after it.'),
  mc('sec-09', BOU, 'Medium',
    'The bridge had been closed for eight months while engineers replaced its corroded steel cables. When it reopened in ______ traffic did not return to the level it had reached before.',
    CONVENTIONS, ['June,', 'June;', 'June', 'June:'], 'A',
    'The introductory clause beginning "When" is followed by a comma before the main clause. The other marks would sever the dependent clause from the sentence it belongs to.'),
  mc('sec-10', BOU, 'Hard',
    'Researchers tracked the wolves by satellite collar for three consecutive winters in the park. The pack ranged much further than anyone had ______ nearly two hundred miles in one season.',
    CONVENTIONS, ['predicted;', 'predicted:', 'predicted,', 'predicted'], 'B',
    'A colon introduces the figure that spells out how much further the pack ranged. A semicolon needs a complete sentence after it, and the phrase that follows is not one.'),
  mc('sec-11', BOU, 'Easy',
    'The old cinema on the corner had been shut for years and its windows boarded over. A local ______ bought the building in 2019 and reopened it as a theater.',
    CONVENTIONS, ['trust, which', 'trust;', 'trust', 'trust,'], 'C',
    'The subject runs straight into its verb, so no punctuation belongs between them. Each of the other options would interrupt the clause or leave it unfinished.'),
  mc('sec-12', BOU, 'Medium',
    'Sailors once navigated the channel by lining up two lights on the headland behind them. The upper light stood on a tower; the ______ much closer to the water, sat on a stone pier.',
    CONVENTIONS, ['lower;', 'lower', 'lower:', 'lower,'], 'D',
    'The phrase "much closer to the water" is nonessential and takes a comma on each side; this is the first. The other marks would separate the subject from its verb.'),
  mc('sec-13', BOU, 'Medium',
    'The glassblowers work in pairs beside a furnace that burns continuously through the night. One shapes the piece while it is still ______ the other keeps it turning so it does not sag.',
    CONVENTIONS, ['molten;', 'molten,', 'molten', 'molten:'], 'A',
    'Two independent clauses need a semicolon when no conjunction joins them. A comma would splice them, and a colon would suggest the second clause explains the first rather than running alongside it.'),
  mc('sec-14', BOU, 'Hard',
    'Marie Tharp spent decades mapping the floor of the Atlantic from soundings taken by ship. Her ______ maps revealed a rift valley running the length of the mid-ocean ridge.',
    CONVENTIONS, ['painstaking, hand-drawn', 'painstaking hand-drawn', 'painstaking; hand-drawn', 'painstaking: hand-drawn'], 'B',
    'The two adjectives are not coordinate, since "hand-drawn maps" acts as a unit that "painstaking" then modifies, so no comma separates them. A semicolon or colon cannot stand between an adjective and the noun it describes.'),
  mc('sec-15', BOU, 'Easy',
    'The festival takes place in a field behind the village hall on the last weekend of August. Visitors come from across the ______ many of them returning year after year.',
    CONVENTIONS, ['county;', 'county.', 'county,', 'county:'], 'C',
    'The phrase that follows describes the visitors but is not a complete sentence, so a comma joins it. A semicolon or full stop would leave a fragment standing alone.'),
  mc('sec-16', BOU, 'Medium',
    'The manuscript had been catalogued as an eighteenth-century copy and left untouched for decades. Conservators examining it in 2018 found something ______ the original binding still intact beneath a later cover.',
    CONVENTIONS, ['unexpected,', 'unexpected;', 'unexpected', 'unexpected:'], 'D',
    'A colon introduces the phrase that identifies what the unexpected thing was. A semicolon requires an independent clause, and the phrase that follows has no verb of its own.'),
  mc('sec-17', BOU, 'Medium',
    'The tram line had run along the seafront since before the war and was much loved locally. It was closed in ______ but the rails were left in place under the tarmac.',
    CONVENTIONS, ['1962,', '1962;', '1962', '1962:'], 'A',
    'A comma goes before the conjunction "but" when it joins two independent clauses. A semicolon would be wrong alongside the conjunction, and omitting punctuation runs the clauses together.'),
  mc('sec-18', BOU, 'Hard',
    'The archive holds the letters of three sisters who wrote to one another every week for forty years. Only one ______ the eldest, ever left the county in which all three were born.',
    CONVENTIONS, ['sister;', 'sister,', 'sister', 'sister:'], 'B',
    'The appositive "the eldest" is set off by a pair of commas, and this is the first of them. A colon or semicolon would break the subject away from its verb.'),
  mc('sec-19', BOU, 'Easy',
    'The kiln is fired only twice a year, and each firing lasts for the better part of a week. The potters load it ______ then seal the door with clay and brick.',
    CONVENTIONS, ['carefully;', 'carefully:', 'carefully and', 'carefully,'], 'C',
    'The two verbs share one subject, so a conjunction joins them without punctuation. A semicolon or colon needs a complete clause on either side, and a comma alone would not link the verbs.'),
  mc('sec-20', BOU, 'Medium',
    'Snow had fallen steadily since the previous evening and the pass was already impassable. The rescue team set out on foot at ______ reaching the stranded climbers before noon.',
    CONVENTIONS, ['dawn;', 'dawn.', 'dawn', 'dawn,'], 'D',
    'The participial phrase beginning "reaching" describes the team and attaches with a comma. A semicolon or full stop would leave it as a fragment.'),
  mc('sec-21', BOU, 'Medium',
    'The composer wrote the quartet in a single fortnight while staying at his sister\'s house. He later claimed it was the only piece of his that he never ______ a single bar.',
    CONVENTIONS, ['revised:', 'revised;', 'revised,', 'revised'], 'A',
    'A colon introduces the phrase that specifies the extent of what he never revised. The other marks would either splice a fragment on or run it into the clause without signalling the specification.'),
  mc('sec-22', BOU, 'Hard',
    'Mangroves grow in the brackish water where rivers meet the sea along tropical coastlines. Their roots trap sediment and slow the ______ as a result, the shoreline behind them erodes far more slowly.',
    CONVENTIONS, ['current,', 'current;', 'current', 'current:'], 'B',
    'Two independent clauses joined by the transitional phrase "as a result" need a semicolon before it. A comma alone would splice the clauses together.'),
  mc('sec-23', BOU, 'Easy',
    'The village school closed in 1998 when the number of pupils fell below a dozen. The building now houses a ______ post office, a café, and a room used for parish meetings.',
    CONVENTIONS, ['trio;', 'trio', 'trio:', 'trio,'], 'C',
    'A colon introduces the list naming the three things the building now houses. A comma would blur the list into the clause and a semicolon requires a full sentence after it.'),
  mc('sec-24', BOU, 'Medium',
    'Ice cores drilled from the Greenland sheet preserve a record of the atmosphere going back millennia. Each layer traps a little ______ sealing in a sample of the air of its year.',
    CONVENTIONS, ['air;', 'air.', 'air:', 'air,'], 'D',
    'The participial phrase beginning "sealing" modifies the clause before it and attaches with a comma. A full stop or semicolon would strand it as a fragment.'),
  mc('sec-25', BOU, 'Medium',
    'The two towns sit on opposite banks of the river and have competed at rowing since 1884. The race is held every ______ the losing crew hosts the dinner afterwards.',
    CONVENTIONS, ['April;', 'April,', 'April', 'April:'], 'A',
    'Both halves stand as complete sentences, so a semicolon joins them. A comma would splice them, and a colon would wrongly present the second clause as an explanation of April.'),

  // ---- Form, Structure, and Sense ----
  mc('sec-26', FSS, 'Easy',
    'Every autumn the same flock gathers on the estuary before continuing south for the winter. The flock of geese ______ south to warmer wetlands as soon as the first frost arrives.',
    CONVENTIONS, ['fly', 'flies', 'are flying', 'have flown'], 'B',
    'The subject is the singular noun "flock", not "geese", so the verb takes the singular form. The phrase "of geese" describes the flock and does not change what the verb agrees with.'),
  mc('sec-27', FSS, 'Medium',
    'The laboratory had been testing three separate samples taken from the same riverbed. Neither the sediment nor the water samples ______ any trace of the contaminant.',
    CONVENTIONS, ['shows', 'has shown', 'showed', 'is showing'], 'C',
    'With "neither ... nor" the verb agrees with the nearer subject, "samples", which is plural, and the surrounding narrative is in the past tense.'),
  mc('sec-28', FSS, 'Medium',
    'The museum acquired the collection in 1954 and has displayed part of it ever since. Each of the four hundred ______ catalogued by hand before the gallery opened.',
    CONVENTIONS, ['objects were', 'objects have been', 'objects are', 'objects was'], 'D',
    'The subject is "Each", which is singular, and the cataloguing happened before a past event, so the singular past form is required.'),
  mc('sec-29', FSS, 'Easy',
    'The coastal path runs for eleven miles between the two harbors and climbs steeply in places. Walkers should carry water, wear sturdy boots, and ______ the tide tables before setting out.',
    CONVENTIONS, ['check', 'checking', 'to check', 'checks'], 'A',
    'The three items in the list must take the same form, and the first two are plain verbs following "should", so the third is as well.'),
  mc('sec-30', FSS, 'Medium',
    'The report was commissioned in 2019 and took almost three years to complete. Having reviewed the evidence from every district, ______ that the scheme should be extended.',
    CONVENTIONS, ['the recommendation was clear', 'the committee recommended', 'it was recommended', 'a recommendation followed'], 'B',
    'The opening phrase describes whoever did the reviewing, so the subject of the main clause must be the party that reviewed the evidence. The other options leave the phrase modifying something that cannot review anything.'),
  mc('sec-31', FSS, 'Hard',
    'The two translations were published a decade apart and take opposite approaches to the original. The earlier one preserves the rhyme scheme; the later one renders each line more ______',
    CONVENTIONS, ['closely then abandons rhyme.', 'close, abandoning rhyme.', 'closely, abandoning rhyme.', 'closer and abandons rhyme.'], 'C',
    'The adverb "closely" modifies the verb "renders", and the participial phrase attaches with a comma. "Close" and "closer" are adjectives and cannot modify a verb.'),
  mc('sec-32', FSS, 'Medium',
    'The company introduced the new system in March and trained its staff over the following weeks. By the time the audit began in ______ every department to the new process.',
    CONVENTIONS, ['September, the company moves', 'September, the company moved', 'September, the company will move', 'September, the company had moved'], 'D',
    'The move finished before the audit began, and both lie in the past, so the past perfect marks the earlier of the two actions.'),
  mc('sec-33', FSS, 'Easy',
    'The bakery opens at five in the morning and sells most of its bread before midday. Its sourdough loaves, which take two days to ______ are the first to sell out.',
    CONVENTIONS, ['prepare,', 'prepare', 'preparing,', 'be preparing,'], 'A',
    'The infinitive "to prepare" completes the clause, and the nonessential clause closes with a comma before the main verb.'),
  mc('sec-34', FSS, 'Medium',
    'The two species look almost identical and were classed together for more than a century. Genetic analysis has now shown that ______ lineages diverged some four million years ago.',
    CONVENTIONS, ['it\'s', 'their', 'there', 'they\'re'], 'B',
    'The possessive "their" is needed before the noun "lineages". "There" is a place, "they\'re" is "they are", and "it\'s" is both singular and a contraction.'),
  mc('sec-35', FSS, 'Hard',
    'The surveyors worked through the summer, mapping every field boundary in the parish. Walking the hedgerows day after day, ______ that several of them predated the enclosure.',
    CONVENTIONS, ['the conclusion was reached', 'it became apparent', 'the surveyors concluded', 'there was evidence'], 'C',
    'The opening phrase describes whoever walked the hedgerows, so the main clause must begin with the people who did the walking. The other options attach the walking to an abstraction.'),
  mc('sec-36', FSS, 'Easy',
    'The orchestra rehearses in a converted chapel on the edge of town three evenings a week. The conductor, along with the two ______ arrives an hour before everyone else.',
    CONVENTIONS, ['soloists, arrive', 'soloists arrive', 'soloists arriving', 'soloists,'], 'D',
    'The subject is the singular "conductor"; the phrase "along with the two soloists" is set off by commas and does not make the subject plural, so the singular verb already in the sentence stands.'),
  mc('sec-37', FSS, 'Medium',
    'The expedition spent four months on the ice and returned with thousands of measurements. Fewer instruments survived the winter than the team ______ at the outset.',
    CONVENTIONS, ['had expected', 'expects', 'has expected', 'will expect'], 'A',
    'The expectation was formed before the winter that has already passed, so the past perfect places it earlier than the other past events described.'),
  mc('sec-38', FSS, 'Medium',
    'The archive contains letters, ledgers and photographs from a single shipping firm. The collection is valuable not only for its ______ but also for its completeness.',
    CONVENTIONS, ['aging', 'age,', 'aged', 'old'], 'B',
    'The construction "not only ... but also" must join grammatically matching elements, and "completeness" is a noun, so the noun "age" is required.'),
  mc('sec-39', FSS, 'Hard',
    'Two scholars have argued about the painting\'s date for the better part of thirty years. Each of them ______ evidence the other regards as decisive against their own case.',
    CONVENTIONS, ['have produced', 'are producing', 'has produced', 'produce'], 'C',
    '"Each" is singular no matter how many people it refers to, so the verb is singular. The plural forms agree with "them" rather than with the actual subject.'),
  mc('sec-40', FSS, 'Easy',
    'The garden was laid out in the 1890s and has been maintained by the same family since. Visitors often remark that the roses are more fragrant than ______ in any public park.',
    CONVENTIONS, ['that', 'it is', 'them', 'those'], 'D',
    'The comparison is between roses and other roses, so the plural "those" stands in for them. "That" and "it" are singular and "them" cannot serve as the subject of the implied clause.'),
  mc('sec-41', FSS, 'Medium',
    'The factory installed new machinery in the spring and retrained its workforce that summer. Output rose sharply, ______ the number of injuries fell for the first time in a decade.',
    CONVENTIONS, ['and', 'and also', 'as well as', 'in addition'], 'A',
    'Two independent clauses separated by a comma need a coordinating conjunction to join them. The other options are not conjunctions and would leave the clauses spliced.'),
  mc('sec-42', FSS, 'Medium',
    'The novel was written in six weeks and published before the end of the following year. Critics at the time praised its structure, its dialogue, and ______ of its central character.',
    CONVENTIONS, ['how it portrayed', 'the portrayal', 'portraying', 'it portrays'], 'B',
    'The three items in the list must match in form, and the first two are noun phrases, so the third must be one too.'),
  mc('sec-43', FSS, 'Hard',
    'The two rivers rise within a mile of one another but reach the sea four hundred miles apart. The northern one, whose course was altered by glaciers, ______ considerably shorter than its neighbor.',
    CONVENTIONS, ['are', 'were', 'is', 'have been'], 'C',
    'The subject is the singular "one"; the clause "whose course was altered by glaciers" sits between the subject and its verb but does not change the agreement.'),
  mc('sec-44', FSS, 'Easy',
    'The choir has sung in the cathedral every Christmas Eve since the end of the war. Its members rehearse weekly from September, and many of them ______ for decades.',
    CONVENTIONS, ['sings', 'has sung', 'is singing', 'have sung'], 'D',
    '"Many of them" is plural, and the singing began in the past and continues, so the present perfect plural is required.'),
  mc('sec-45', FSS, 'Medium',
    'The telescope was built on a ridge because the air there is thin and unusually still. Astronomers chose the site for its altitude, its dryness, and ______ from city lights.',
    CONVENTIONS, ['its distance', 'being distant', 'how distant it is', 'that it is distant'], 'A',
    'The list requires three matching noun phrases, and the first two begin with "its", so the third does as well.'),
  mc('sec-46', FSS, 'Medium',
    'The lighthouse keeper kept a daily log for thirty-one years without missing an entry. Reading through the volumes, ______ struck by how rarely the weather is mentioned at all.',
    CONVENTIONS, ['the impression is', 'a visitor is', 'it seems', 'there is a sense'], 'B',
    'The opening phrase describes whoever is doing the reading, so the main clause must name a person who can read. The other options leave the phrase dangling.'),
  mc('sec-47', FSS, 'Hard',
    'The seeds lay in the dry soil for eleven years before any rain fell on the plain. When the storms finally came, the plants grew, flowered and ______ within a single fortnight.',
    CONVENTIONS, ['were setting seed', 'set seed', 'had set seed', 'would set seed'], 'B',
    'The three verbs share a subject and must match in form, and the first two are simple past, so the third is as well.'),
  mc('sec-48', FSS, 'Medium',
    'The two designs were submitted anonymously and judged by a panel of seven architects. The winning entry was simpler than ______ the panel had considered that year.',
    CONVENTIONS, ['any', 'any other one', 'any of the others', 'the others'], 'C',
    'The comparison needs a phrase that names the remaining entries as a group, which "any of the others" does. "Any" alone would illogically include the winning entry itself.'),
  mc('sec-49', FSS, 'Easy',
    'The path along the cliff was rebuilt after a landslip closed it for the whole of one winter. Walkers who use it now ______ that the new route is considerably safer.',
    CONVENTIONS, ['agree', 'agrees', 'is agreeing', 'has agreed'], 'A',
    'The subject is the plural "Walkers", so the verb is plural. The clause "who use it now" describes the walkers and does not alter the agreement.'),
  mc('sec-50', FSS, 'Medium',
    'The two manuscripts were copied in the same workshop within a few years of one another. Although the hands are similar, the older of the two ______ a distinctive way of forming the letter g.',
    CONVENTIONS, ['have', 'has', 'are having', 'having'], 'B',
    'The subject is "the older of the two", which is singular, so the verb is singular. "Having" would leave the sentence without a main verb at all.'),
];
